### ISSUE TITLE
OpenRPC spec with invalid Request examples?

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#112]
I've played a little bit with our `openrpc.json` specification in the https://playground.open-rpc.org/ (its fun!) and noticed that the `panda_getEntryArguments` example is invalid when I use the "Try" feature:

It gives me this request format, with the parameters formatted as an array:

```json
{
    "jsonrpc": "2.0",
    "method": "panda_getEntryArguments",
    "params": [
        "2deee1fac104aaac753377bbc2ff70fa5d5154abdac4b4577392db88de6a9a49",
        "00401d76566758a5b6bfc561f1c936d8fc86b5b42ea22ab1dabf40d249d27dd906401fde147e53f44c103dd02a254916be113e51de1077a946a3a0c1272b9b348437"
    ],
    "id": 0
}
```

.. but I would expect the following, with the parameters formatted as an object:

```json
{
    "jsonrpc": "2.0",
    "method": "panda_getEntryArguments",
    "params": {
        "author": "2deee1fac104aaac753377bbc2ff70fa5d5154abdac4b4577392db88de6a9a49",
        "schema":  "00401d76566758a5b6bfc561f1c936d8fc86b5b42ea22ab1dabf40d249d27dd906401fde147e53f44c103dd02a254916be113e51de1077a946a3a0c1272b9b348437"
    },
    "id": 0
}
```

Is this an issue with the playground or do we have to indicate in the spec that we expect objects rather than array in our RPC methods?

Ping @sandreae

**Comment by sandreae** [comment]
Hmmm.... not sure.

Did you try making a call to the welle using valid parameter values? I just did and get a successful response containing correct next entry args.

**Comment by sandreae** [comment]
It is fun to play around with!!! This could be our primary p2panda client :rofl:

**Comment by adzialocha** [comment]
> Did you try making a call to the welle using valid parameter values? I just did and get a successful response containing correct next entry args.

Only tried after manually changing to the correct request value, then it works smoothly 🤩 Does it also work with array params?

**Comment by sandreae** [comment]
Yeh, it works with the array params too (if the values are correct... the default ones don't work cos they are our test values).

**Comment by adzialocha** [comment]
Maybe one needs to write `params: { ... }` instead of `params: [ ... ]`?

**Comment by sandreae** [comment]
Ok, did some digging around. json-rpc is happy with either a correctly ordered array OR named object, so these are both valid. But for us, we want named params, in which case you need to set the following on the method object in the open-rpc spec.

`"paramStructure": "by-name"`

I've done that now, so it looks as we expect. I also added a bit more info and the node url :heart_eyes: 

I'm gunna close this, thanks for spotting this!

**Comment by adzialocha** [comment]
> json-rpc is happy with either a correctly ordered array OR named object

Interesting, learned something new about JSON RPC 🤩
