### ISSUE TITLE
Define test strategy for `wasm` module

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#115]
Thinking about this for the future when this lib grows and it might be useful to put boundaries on what implementations in wasm.rs (or its successor) should and shouldn't do (scope).

Related: https://github.com/p2panda/p2panda/pull/111#pullrequestreview-776599797

**Comment by sandreae** [comment]
Bumping this.... I just made loads of breaking changes in `p2panda-rs` and as there are no tests in the `rs` wasm code then everything passed happily. lolz. Should probably have at least minimal checks on the rust side of the wasm pipeline.
