### ISSUE TITLE
Change to new `rustdoc::missing_doc_code_examples` linter name

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#120]
```
warning: lint `missing_doc_code_examples` has been renamed to `rustdoc::missing_doc_code_examples`
  --> /home/adz/dev/p2panda/p2panda/p2panda-rs/src/lib.rs:48:5
   |
48 |     missing_doc_code_examples,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ help: use the new name: `rustdoc::missing_doc_code_examples`
   |
   = note: `#[warn(renamed_and_removed_lints)]` on by default
```

The new linter name breaks building `aquadoggo` since its docker image uses an older Rust compiler. We can use the new name as soon as version `1.52.0` gets supported in `ekidd/rust-musl-builder` (https://hub.docker.com/r/ekidd/rust-musl-builder/tags).

Related: https://github.com/p2panda/aquadoggo/issues/40

**Comment by cafca** [comment]
I think it's supported already but they are not publishing on docker hub anymore because of the pricing changes

https://github.com/emk/rust-musl-builder/issues/123#issuecomment-882098613

**Comment by cafca** [comment]
Related: https://github.com/emk/rust-musl-builder/pull/126

**Comment by adzialocha** [comment]
> I think it's supported already but they are not publishing on docker hub anymore because of the pricing changes

As I understood it now they can publish it on Docker Hub but not use it to build the images beforehands there, so they will move the CI for building to GitHub action and continue publishing on Docker Hub. Let's wait until [emk/rust-musl-builder#126](https://github.com/emk/rust-musl-builder/pull/126) is merged and the CI re-established again.

**Comment by adzialocha** [comment]
This is ready now :sparkler:
