### ISSUE TITLE
Failing teardown in test suite

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#124]
Running the test suite results in:

```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.
```

Running with `detectOpenHandles` doesn't surface the tests that cause this.

**Comment by sandreae** [comment]
I tried running the tests with `--detectOpenHandles` flag (as recommended) but then there is actually no error and the tests even run quite a bit faster :raised_eyebrow:

**Comment by sandreae** [comment]
I also tried running each test suite individually, but the the error doesn't show for any of them.
