### ISSUE TITLE
Validating a DAG

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#127]
Working on the DAG construction in our early stage materializer and I wondered the following. How much DAG validation do we need as these cases are impossible if we are passing in well formed entries in a bamboo log?

- There should be exactly one root node
- There should be no disconnected nodes
- There should be no cycles

Answers on a postcard please.

**Comment by adzialocha** [comment]
I wonder if some sort of validation should happen *before* it arrives at the Materializer. I'm not sure if this is possible, but we should have a jam on validating p2panda data integrity in general and maybe actually by doing it properly we can be sure that all data which arrives already that deep into materialization will be fine.
