### ISSUE TITLE
Validating UPDATE messages

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#133]
We will soon have a `Schema` struct which can validate `MessageField` content against schemas. However, when publishing UPDATE messages, we are planning for these to only contain the updated fields (right?). What is our approach to validation in this case?

**Comment by sandreae** [comment]
One approach would be to have a separate UPDATE schema which validated against anyOf the existing field key values.

**Comment by adzialocha** [comment]
> One approach would be to have a separate UPDATE schema which validated against anyOf the existing field key values.

This sounds good, it could be part of the same CDDL definition.

**Comment by sandreae** [comment]
We could use sockets for this: https://cbor-wg.github.io/cddl/draft-ietf-cbor-cddl.html#socketplug

Something like:

```
operation = {
    schema: hash,
    version: 1,
    operation-body,
}

hash = tstr .regexp "[0-9a-f]{68}"

; Create operation
operation-body = (
    action: "create", fields: $$create-operation-fields //
    action: "update", fields: $$update-operation-fields, previousOperations: [1* hash] //
    action: "delete", previousOperations: [1* hash]
)

; then somewhere else:

$$create-operation-fields //= (
    age: { type: \"int\", value: int },
    name: { type: \"str\", value: tstr }
)

$$update-operation-fields //= (
    ? age: { type: \"int\", value: int },
    ? name: { type: \"str\", value: tstr }
)
```
