### ISSUE TITLE
Expand `Operation` to contain `previous_operation`

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#135]
And also maybe `instance_author`.

It should look something like this:

```
{
    action: "CREATE” | “UPDATE" | "DELETE"
    schema: <HASH>
    instance_id: <HASH>
    instance_author: <PUBLIC_KEY>
    ? previousOp: <HASH>
    ? fields: [{
        "<FIELD KEY>": <VALUE> 
        "<FIELD VALUE>": <VALUE>
    }]
}
```

Spec being drafted [here](https://laub.liebechaos.org/7cGHWPCcR8eoZBkk-X9R4w)

**Comment by cafca** [comment]
I propose calling the field `previous_operation` to stick to snake case and be easy to read.

**Comment by adzialocha** [comment]
What is `instance_author` doing?

**Comment by sandreae** [comment]
Now we're aiming for this:

```
{
    action: "CREATE” | “UPDATE" | "DELETE"
    schema: <HASH>
    version: <NUMBER>
    ? previous_operations: <HASH>
    ? fields: [{
        "<FIELD KEY>": <VALUE> 
        "<FIELD VALUE>": <VALUE>
    }]
}
```

**Comment by adzialocha** [comment]
Guess this happened during copy paste but is `previous_operations` really only a hash?

**Comment by sandreae** [comment]
> Guess this happened during copy paste but is `previous_operations` really only a hash?

corrected, thanks!
