### ISSUE TITLE
Replace YAMF hash with YASMF hash

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#138]
YASMF brings us Blake3 hashes.

# Requirements

- Replace `bamboo-rs-core` with [`bamboo-rs-core-ed25519-yasmf`](https://crates.io/crates/bamboo-rs-core-ed25519-yasmf)
- Replace `yamf-hash` with [`yasmf-hash`](https://crates.io/crates/yasmf-hash)
- Update documentation

**Comment by adzialocha** [comment]
Related: https://github.com/p2panda/p2panda/issues/19
