### ISSUE TITLE
Generate more complex `test-data` 

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#183]
Currently the test data we generate in `test_utils` and use in `p2panda-js` contains one author, who has one log (document) which has 4 entries (create -> update -> update -> delete). If we want to test more complex situations (multiple documents, with different collections of entries, multiple authors) we need to rethink how the test data is composed and consumed.

**Comment by adzialocha** [comment]
This can be closed now since we left JSON RPC, right @sandreae?
