### ISSUE TITLE
Problems importing `p2panda-js` with `svelte-kit`

### ISSUE THREAD

**Issue by wighawag** [p2panda/p2panda#189]
Hi, I have encountered issues with [svelte-kit](https://kit.svelte.dev/) and even raw [vite](https://vitejs.dev/) and this I think stem from the fact that the webpack config generate es5 file.

It would be great if p2panda-js could provide a more modern output to be used by modern framework that expect es6 module.

typescript should be able to generate them without the need for webpack. but not familiar with lib that include wasm dependencies

**Comment by adzialocha** [comment]
Thank you @wighawag for that note! Can you link to the project where you tried to use the library? We should be able to change the Webpack settings regardless of the wasm tricks without any problem but it would be good to test the outcomes directly.

**Comment by wighawag** [comment]
Hi @adzialocha I created a repo exhibiting the issue : https://github.com/bug-reproduction/p2-panda-svelte-kit

**Comment by adzialocha** [comment]
> Hi @adzialocha I created a repo exhibiting the issue : https://github.com/bug-reproduction/p2-panda-svelte-kit

Thank you! When I try to run it on my machine it shows this error here?

```
request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
Error: request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
    at Object.get request [as request] (file:///home/adz/dev/p2-panda-svelte-kit/node_modules/@sveltejs/kit/dist/chunks/index.js:1746:11)
    at Object.handle (/home/adz/dev/p2-panda-svelte-kit/src/hooks.ts:5:48)
    at respond (file:///home/adz/dev/p2-panda-svelte-kit/node_modules/@sveltejs/kit/dist/chunks/index.js:1653:30)
    at file:///home/adz/dev/p2-panda-svelte-kit/node_modules/@sveltejs/kit/dist/chunks/index.js:1978:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by wighawag** [comment]
HI @adzialocha What did you do to get this ?

I get the error mentioned in the OP this way: 

# Setup 

(note the use of pnpm but the same should happen with npm (but as the repo do not have a npm lock file it might not be the exact same error))

```sh
git clone git@github.com:bug-reproduction/p2-panda-svelte-kit.git
cd p2-panda-svelte-kit
pnpm i
```

# execution

## in dev environment :

```sh
pnpm dev
```

navigate to http://localhost:3000

and you get

### server (in your terminal console):

```
panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("missing field `type`"), offset: 0 }', src/message/message.rs:348:61

Stack:

Error
    at module.exports.__wbg_new_59cb74e423758ede (/home/wighawag/dev/tmp/p2-panda-svelte-kit-cloned/node_modules/.pnpm/p2panda-js@0.2.1/node_modules/p2panda-js/lib/wasm/index.js:546:15)
    at <anonymous>:wasm-function[185]:0x6d46b
    at <anonymous>:wasm-function[568]:0x7aa19
    at <anonymous>:wasm-function[292]:0x75c3a
    at <anonymous>:wasm-function[341]:0x77e7d
    at <anonymous>:wasm-function[421]:0x79bd5
    at <anonymous>:wasm-function[433]:0x79e47
    at <anonymous>:wasm-function[353]:0x78493
    at <anonymous>:wasm-function[205]:0x6f3f9
    at <anonymous>:wasm-function[109]:0x623e3


panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("missing field `type`"), offset: 0 }', src/message/message.rs:348:61

Stack:

Error
    at module.exports.__wbg_new_59cb74e423758ede (/home/wighawag/dev/tmp/p2-panda-svelte-kit-cloned/node_modules/.pnpm/p2panda-js@0.2.1/node_modules/p2panda-js/lib/wasm/index.js:546:15)
    at <anonymous>:wasm-function[185]:0x6d46b
    at <anonymous>:wasm-function[568]:0x7aa19
    at <anonymous>:wasm-function[292]:0x75c3a
    at <anonymous>:wasm-function[341]:0x77e7d
    at <anonymous>:wasm-function[421]:0x79bd5
    at <anonymous>:wasm-function[433]:0x79e47
    at <anonymous>:wasm-function[353]:0x78493
    at <anonymous>:wasm-function[205]:0x6f3f9
    at <anonymous>:wasm-function[109]:0x623e3


(node:2391223) UnhandledPromiseRejectionWarning: RuntimeError: unreachable
    at <anonymous>:wasm-function[292]:0x75c70
    at <anonymous>:wasm-function[341]:0x77e7d
    at <anonymous>:wasm-function[421]:0x79bd5
    at <anonymous>:wasm-function[433]:0x79e47
    at <anonymous>:wasm-function[353]:0x78493
    at <anonymous>:wasm-function[205]:0x6f3f9
    at <anonymous>:wasm-function[109]:0x623e3
    at <anonymous>:wasm-function[69]:0x5836a
    at decodeEntry (<anonymous>:wasm-function[358]:0x786aa)
    at module.exports.decodeEntry (/home/wighawag/dev/tmp/p2-panda-svelte-kit-cloned/node_modules/.pnpm/p2panda-js@0.2.1/node_modules/p2panda-js/lib/wasm/index.js:277:20)
```

### browser :

```
500
Automatic publicPath is not supported in this browser
Error: Automatic publicPath is not supported in this browser
    at http://localhost:3000/node_modules/.vite/p2panda-js.js?v=358c015e:3076:19
    at http://localhost:3000/node_modules/.vite/p2panda-js.js?v=358c015e:3078:11
    at http://localhost:3000/node_modules/.vite/p2panda-js.js?v=358c015e:3079:9
    at http://localhost:3000/node_modules/.vite/p2panda-js.js?v=358c015e:9:82
    at node_modules/.pnpm/p2panda-js@0.2.1/node_modules/p2panda-js/lib/index.min.js (http://localhost:3000/node_modules/.vite/p2panda-js.js?v=358c015e:10:6)
    at __require (http://localhost:3000/node_modules/.vite/chunk-Z47AEMLX.js?v=358c015e:2:44)
    at http://localhost:3000/node_modules/.vite/p2panda-js.js?v=358c015e:3085:26
```

## in build environment :
```sh
pnpm build
pnpm preview
```

navigate to http://localhost:3000

and you get

### server (in your terminal console):
```

file:///home/wighawag/dev/tmp/p2-panda-svelte-kit-cloned/.svelte-kit/output/server/entries/pages/index.svelte.js:2
import { Session } from "p2panda-js";
         ^^^^^^^
SyntaxError: Named export 'Session' not found. The requested module 'p2panda-js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'p2panda-js';
const { Session } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:121:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:166:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Promise.all (index 1)
    at async respond$1 (file:///home/wighawag/dev/tmp/p2-panda-svelte-kit-cloned/.svelte-kit/output/server/app.js:1002:13)
    at async render_page (file:///home/wighawag/dev/tmp/p2-panda-svelte-kit-cloned/.svelte-kit/output/server/app.js:1163:20)
    at async resolve (file:///home/wighawag/dev/tmp/p2-panda-svelte-kit-cloned/.svelte-kit/output/server/app.js:1398:104)
    at async Object.handle (file:///home/wighawag/dev/tmp/p2-panda-svelte-kit-cloned/.svelte-kit/output/server/app.js:1481:20)
    at async respond (file:///home/wighawag/dev/tmp/p2-panda-svelte-kit-cloned/.svelte-kit/output/server/app.js:1369:12)
    at async render_handler (file:///home/wighawag/dev/tmp/p2-panda-svelte-kit-cloned/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.232_svelte@3.46.2/node_modules/@sveltejs/kit/dist/chunks/index6.js:106:6)
```

### browser :

```
500
Named export 'Session' not found. The requested module 'p2panda-js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'p2panda-js';
const { Session } = pkg;
SyntaxError: Named export 'Session' not found. The requested module 'p2panda-js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'p2panda-js';
const { Session } = pkg;
```

**Comment by adzialocha** [comment]
> HI @adzialocha What did you do to get this ?

Hello @wighawag! Ah ja, I've used `npm` instead of `pnpm` (didn't know it before, looks interesting) and indeed this solved the issue (I guess `npm` installed different versions than the ones in the pnpm lockfile).

Regarding the issues I think there is one answer to the server one:

> panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("missing field `type`"), offset: 0 }', src/message/message.rs:348:61

Your application points against our node (*https://welle.liebechaos.org*) which in itself is fine, it just uses a very old version of p2panda. So it fetches the data from the node via your `sync` task but fails since your `p2panda-js` library is already newer. In the future we don't want to run into problems like this (clearly use versioning and support legacy formats) but since p2panda is not stable yet everything is a little bit out of sync.

I would recommend using the latest versions which would require you do build `p2panda-js` yourself. Soon we gonna make a `0.3.0`, then you can skip this step:

1. Clone `p2panda` repository and move into `p2panda-js` folder
2. Run `npm install` and `npm run build`
3. Link the builded package via `npm link`
4. Move into your svelte project and run `npm link p2panda-js`

Now you're using the latest version.

Also you can run your own node which also supports the latest version by compiling the aquadoggo: https://github.com/p2panda/aquadoggo. We will change the version of https://welle.liebechaos.org soon as well to the latest aquadoggo implementation.

**Comment by adzialocha** [comment]
> Named export 'Session' not found. The requested module 'p2panda-js' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example using:

We can try exporting the library differently but I guess you can solve it temporarily by writing the imports like mentioned in the logs:

```
import p2panda from 'p2panda-js';
const { Session } = p2panda;
```

**Comment by wighawag** [comment]
Thanks @adzialocha for the help,

I linked the library with the latest from github but I now get this error :

```
500
require is not defined
ReferenceError: require is not defined
    at Object.5315 (/@fs/home/wighawag/dev/p2panda/p2panda/p2panda-js/lib/index.js:9029:1)
    at __webpack_require__ (/@fs/home/wighawag/dev/p2panda/p2panda/p2panda-js/lib/index.js:9177:42)
    at Object.7278 (/@fs/home/wighawag/dev/p2panda/p2panda/p2panda-js/lib/index.js:2084:36)
    at __webpack_require__ (/@fs/home/wighawag/dev/p2panda/p2panda/p2panda-js/lib/index.js:9177:42)
    at eval (/@fs/home/wighawag/dev/p2panda/p2panda/p2panda-js/lib/index.js:9188:37)
    at eval (/@fs/home/wighawag/dev/p2panda/p2panda/p2panda-js/lib/index.js:9191:12)
    at webpackUniversalModuleDefinition (/@fs/home/wighawag/dev/p2panda/p2panda/p2panda-js/lib/index.js:11:21)
    at eval (/@fs/home/wighawag/dev/p2panda/p2panda/p2panda-js/lib/index.js:12:3)
    at instantiateModule (/home/wighawag/dev/tmp/p2-panda-svelte-kit-cloned/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60105:15)

```

**Comment by adzialocha** [comment]
Svelte seems to link to the NodeJS build of `p2panda-js` which uses `require` statements: `/@fs/home/wighawag/dev/p2panda/p2panda/p2panda-js/lib/index.js:9029:1`.

The browser build (`index.min.js`) does not contain them .. in WebPack this is identified automatically depending on the build target, not sure how it works with svelte?

**Comment by adzialocha** [comment]
I've had another look at this and realized that svelte has a quite custom way of approaching modules. I don't think this is a "bug" but rather a feature we do not support (aka svelte module support). 

We can look into this after we understood better what Svelte needs (I'm not a Svelte developer).

**Comment by wighawag** [comment]
Hi @adzialocha sorry did not have a chance to look at that back.

But to give more context, most people using svelte will use vite (https://vitejs.dev/) to handle module loading and this is also what svelte-kit do

vite expect `es modules` and so if p2panda were exporting es6 module it should work

**Comment by adzialocha** [comment]
Thanks for writing @wighawag !

We've been just looking into all the different kinds of exporting modules. Its not too trivial but I assume this issue can be tackled by solving this one then? https://github.com/p2panda/p2panda/issues/438

**Comment by wighawag** [comment]
Yes nowadays for browser es module is the new norm so you want that and while nodejs is kind of supporting es module you still probably want cjs.

After that you have to make sure you use libraries that work in both browser and node so that way you do not need tool like webpack to inject stuff for you

**Comment by adzialocha** [comment]
We just changed our building pipeline from Webpack and Rollup which made it much easier to bundle p2panda for all sorts of module formats. The latest release supports UMD, CommonJS and ESM modules next to NodeJS builds. Here you find more information:

https://www.npmjs.com/package/p2panda-js
https://cdn.jsdelivr.net/npm/p2panda-js@0.5.0/lib/
Documentation: https://p2panda.org/handbook/lib/p2panda-js/

The library design changed slightly to a more "low-level" design, to be closer to the Rust crate API but also to allow developers to build their own "p2panda" frameworks on top of this "toolbox". One first framework for TypeScript is in development here: https://github.com/p2panda/shirokuma

In any case, I hope that `p2panda-js` works now with Svelte? If you find time, could you give it a check @wighawag ? Thank you!

**Comment by wighawag** [comment]
Nice!
Was just looking at testing but the demo code is using 0.3.0 instead of 0.5.0 and there seems to be breaking changes, no Session from `p2panda-js` anymore for example.
Happy to test, but want to make sure I test the right thing :)

**Comment by adzialocha** [comment]
> Nice! Was just looking at testing but the demo code is using 0.3.0 instead of 0.5.0 and there seems to be breaking changes, no Session from `p2panda-js` anymore for example. Happy to test, but want to make sure I test the right thing :)

Yes, the `Session` moved into `shirokuma`, as this is the more high-level framework now (not released yet). For now it would be cool if you could test `p2panda-js`? Thank you!

**Comment by wighawag** [comment]
Ok, yes it seems that p2panda-js works. The only thing I tested is to create a KeyPair

**Comment by adzialocha** [comment]
> Ok, yes it seems that p2panda-js works. The only thing I tested is to create a KeyPair

Amazing! Thank you so much! :sparkles:
