### ISSUE TITLE
Tests fail when running aquadoggo on port 2020 while running test suite

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#193]
The p2panda-js test suite runs a mock node on port 2020. When another node (aquadoggo) is running on that port before starting the test suite, the tests will (probably) fail because they will connect to that running node instead of the mock node.

Expected:

There is some error message that the port required for the test suite is already being used.

**Comment by sandreae** [comment]
If the `aquadoggo` instance running contained _exactly_ the right entries for our test suite, I guess the tests should then pass again :rofl:

**Comment by adzialocha** [comment]
> There is some error message that the port required for the test suite is already being used.

When I run `npm test` while port 2020 is occupied I already receive the following warning:

```
Error: listen EADDRINUSE: address already in use :::2020
```

**Comment by adzialocha** [comment]
Is this issue resolved @cafca? It looks like the requested error message exists :+1:
