### ISSUE TITLE
Revisit `OperationWithMeta` and `Operation` relationship

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#198]
`Operation` currently is a struct that contains the contents of a decoded `OperationEncoded`. However, as we are moving to handling documents (and further), operations become a much more central concept to p2panda than before, when we were mostly concerned with handling and processing entries. `OperationWithMeta` has already been introduced to wrap both an `Operation` as well as metadata about its author. 

At first thought we could use entries instead of `OperationWithMeta` but entries may not contain the actual operation data as that is optional.

Rename:

- `OperationWithMeta` -> `Operation`
- `Operation` -> `OperationRaw` (?)

---

_Previous issue description to provide context to discussion below_

The name `OperationWithMeta` can be improved to reflect what the role of this struct is. Conceptually, the original `Operation` doesn't carry any information about its author or the entry it was published in. It exists independent of authorship and only describes a change to a document. `OperationWithMeta` on the other side contains information about the author of the change and the entry it was published in. We also have `OperationEncoded`, which also doesn't carry author information but is encoded in CBOR. 

I think it would be good to name it `OperationSigned` to show that it represents an operation that has been signed (and published) by an author.

* **Entry** raw entry data (no author)
* **EntrySigned** Bamboo-encoded entry + signature
* **Operation** raw data change (no author)
* **OperationEncoded** CBOR-encoded operation (no author)
* **OperationSigned** raw data change + id of author & signed entry

**Comment by adzialocha** [comment]
How does the "withMeta" suffix not entail this for you?

Re: "OperationSigned", I'm not sure if it signals the wrong information, since operations are not directly signed, but Entries are, of which operations are the payload, so they are indirectly signed instead. When I read "OperationSigned" I assume I'll find a signature of an operation.

How about "OperationBundle"?

**Comment by cafca** [comment]
Maybe we actually don't need this type to be `pub` at all and then it doesn't matter so much.

**Comment by sandreae** [comment]
> Maybe we actually don't need this type to be `pub` at all and then it doesn't matter so much.

Yes, I think it could be a private type :+1:

**Comment by sandreae** [comment]
We could also move everything "meta" we need directly into `Operation` and remove this struct all together. We could have an optional `meta` field which contains `OperationMeta` (we have this pattern already elsewhere) and then we have a method for decoding an operation with meta data attached which would also need the corresponding entry.

**Comment by cafca** [comment]
After the last week I saw the need for `OperationWithMeta` in lots of places outside of `Document`, I think it would be better not to have it private. 

I like the idea of making `Operation` a *rich* struct that has embedded metadata!

**Comment by sandreae** [comment]
I'd like to move this out of schema milestone too :wave:

**Comment by adzialocha** [comment]
From a discussion here https://laub.liebechaos.org/leTbMWT1Qj6btn7-o6xrWA# we could think about calling it `VerifiedOperation` or `OperationVerified`?

**Comment by cafca** [comment]
YES! I used to be in favor of the `OperationX` pattern for naming because it sorts nicer but it's so awkward to say all the time that I now favor `XOperation` (`VerifiedOperation`)

**Comment by sandreae** [comment]
Really like this!! It is exactly what it is 🙂

**Comment by sandreae** [comment]
I'm still in favour of this rename when all the dust settles from the current changes.

**Comment by sandreae** [comment]
_After_ we've finished this round of `aquadoggo` mayhem, I suggest the following actions:

1) Rename `OperationWithMeta` to `VerifiedOperation`
2) Merge `AsOperationWithMeta` and `AsStorageOperation` traits into `AsVerifiedOperation`
3) Impl this new trait on `VerifiedOperation` and us it as the required trait in `OperationStore`

This would mean we wouldn't need a implementation specific struct to represent `StorageOperation` we can just use `VerifiedOperation`

**Comment by sandreae** [comment]
related: https://github.com/p2panda/p2panda/issues/320

**Comment by cafca** [comment]
I think I am assigned this from the original issue creation. I would love to do this but will unassign myself as I am not working on this right now.

**Comment by sandreae** [comment]
I thought I might have a go at this... I'm on a house-keeping roll.

**Comment by sandreae** [comment]
Hmmm, just realised that `AsOperationWithMeta` trait (as it is before renaming) can't be used in place of `AsStorageOperation` because the latter knows about it's `document_id` whereas the former doesn't :raised_eyebrow:

**Comment by sandreae** [comment]
I'm trying to figure out how best to represent these relationships between the various states of operation we have. I see that there are three layers:

- `Operation` an operation in it's native form, hasn't become a payload on an entry yet, doesn't know about documents really
- `VerifiedOperation` has been hashed and encoded on a signed entry, contains an `OperationId` & `Author`
- `StorageOperation` has been accepted on a node and placed within a document, knows about all of the above plus `DocumentId` (also any other meta data a node implementer may wish to keep around)

Using traits, I could see these being represented like:

## Traits definitions

```rust
pub trait AsOperation {
    /// Returns true if previous_operations contains a document view id.
    fn has_previous_operations(&self) -> bool {
        self.previous_operations().is_some()
    }

    /// Returns true when instance is CREATE operation.
    fn is_create(&self) -> bool {
        self.action() == OperationAction::Create
    }

    /// Returns true when instance is UPDATE operation.
    fn is_update(&self) -> bool {
        self.action() == OperationAction::Update
    }

   // etc...
}

pub trait AsVerifiedOperation {
    /// Returns the identifier for this operation.
    fn operation_id(&self) -> &OperationId;

    /// Returns the public key of the author of this operation.
    fn public_key(&self) -> &Author;

    /// Returns the wrapped operation.
    fn operation(&self) -> &Operation;
}

pub trait AsStorageOperation: Sized + Clone + Send + Sync {
    /// The id of the document this operation is contained within.
    fn document_id(&self) -> &DocumentId;

    /// The id of the document this operation is contained within.
    fn verified_operation(&self) -> &VerifiedOperation;
}
```

## Trait implementations (with generics)

```rust
#[derive(Debug, Clone)]
pub struct StorageOperation {
    operation: VerifiedOperation,
    document_id: DocumentId,
}

impl AsStorageOperation for StorageOperation {
    type AsStorageOperationError = crate::operation::OperationError;

    fn document_id(&self) -> &DocumentId {
        &self.document_id
    }

    fn verified_operation(&self) -> &VerifiedOperation {
        &self.operation
    }
}

impl<T: AsStorageOperation> AsVerifiedOperation for T {
    fn operation_id(&self) -> &OperationId {
        self.verified_operation().operation_id()
    }

    fn public_key(&self) -> &Author {
        self.verified_operation().public_key()
    }

    fn operation(&self) -> &Operation {
        self.verified_operation().operation()
    }
}

impl<T: AsVerifiedOperation> AsOperation for T {
    /// Returns action type of operation.
    fn action(&self) -> OperationAction {
        self.operation().action()
    }

    /// Returns schema of operation.
    fn schema(&self) -> SchemaId {
        self.operation().schema()
    }

    /// Returns version of operation.
    fn version(&self) -> OperationVersion {
        self.operation().version()
    }

    /// Returns application data fields of operation.
    fn fields(&self) -> Option<OperationFields> {
        self.operation().fields()
    }

    /// Returns vector of this operation's previous operation ids
    fn previous_operations(&self) -> Option<DocumentViewId> {
        self.operation().previous_operations()
    }
}


```

I quite like this. The reason being that when implementing `AsStorageOperation` for example, you get all the generic implementations for `AsVerifiedOperation` and `AsOperation` free. I also think it quite nicely demonstrates the differences between these different states an operation can be in. I also think it's easy to read... but I might be wrong about that....

@adzialocha @cafca what do you think? 

Please also feel free to say "I don't care, just leave the module be and rename the struct `VerifiedOperation`" :rofl: :rofl:

**Comment by adzialocha** [comment]
@sandreae I like it and agree, its easy to understand. The concept of "storage" of course its a little bit abstract in the naming of `AsStorageOperation`, especially it does not _really_ explain why there is suddenly a `document_id` (thats a condition of materialization which is somewhat related to persistence) but I can see how it aligns with the naming scheme of all other storage traits :+1:

**Comment by sandreae** [comment]
Ok, interesting. I think we can do without `document_id`. It would mean we either pass in the document_id separately in `insert_operation()` or we hit the db once more inside that method to retrieve the document_id (I would prefer the latter).

Then we don't need any specialist storage trait, we can just require `AsVerifiedOperation` inside `OperationStore`.

**Comment by adzialocha** [comment]
> Ok, interesting. I think we can do without `document_id`. It would mean we either pass in the document_id separately in `insert_operation()` or we hit the db once more inside that method to retrieve the document_id (I would prefer the latter).
> 
> Then we don't need any specialist storage trait, we can just require `AsVerifiedOperation` inside `OperationStore`.

This sounds nice and simple! :+1:

**Comment by sandreae** [comment]
I liiiiike simple 😝

**Comment by sandreae** [comment]
I think this is the right approach, I'm gunna wait until the big replication PR is merged in aquadoggo before implementing it though.

**Comment by adzialocha** [comment]
Is this now merged @sandreae?

**Comment by sandreae** [comment]
Ah, jaaa! https://github.com/p2panda/p2panda/pull/353
