### ISSUE TITLE
Define author encoding

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#20]
How do we present an author's public key to users?

* Hexadecimal `1a8a62c5f64eed987326513ea15a6ea2682c256ac57a418c1c92d96787c8b36e` (64 chars)
* Base64 (ala SSB) `GopixfZO7ZhzJlE+oVpuomgsJWrFekGMHJLZZ4fIs24=` (43 chars)
* Base64url `GsKKYsOFw7ZOw63CmHMmUT7CoVpuwqJoLCVqw4V6QcKMHMKSw5lnwofDiMKzbg==` https://tools.ietf.org/html/rfc4648#section-5

**Comment by cafca** [comment]
How about emoji encoding?

**Comment by adzialocha** [comment]
https://github.com/AdamNiederer/base100
