### ISSUE TITLE
Rework `previous_operations`

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#204]
- `previous_operations` doesn't need to be an option. Instead we can tell serde to skil serialising it when empty ?
- rename `previous_operations` to `document_tips` ?
- don't include backlink in previous_operations. ?

**Comment by sandreae** [comment]
Just collecting another thought about previous_operations:

It could be an enum? None, SinglePredecessor, MultiPredecessors or something like that.

**Comment by sandreae** [comment]
I'd like to move this out of the schema milestones, is that ok?

**Comment by adzialocha** [comment]
> I'd like to move this out of the schema milestones, is that ok?

Agreed!

**Comment by sandreae** [comment]
I've been reflecting on what this particular point would involve:

> don't include backlink in previous_operations.

I think there are some benefits, then main one being that a high percentage of encoded operations will be smaller, but obviously it also adds some "magic" complexity into the system.

I'm not sure if we are still interested in doing this, if we did I think it would look like:

- Alter validation of operations to allow `previous_operations = None` for `UPDATE` & `DELETE` operations.
- When we decode operations and store them in the db, we would need to derive `previous_operations` from an operations' entry when it isn't provided.
- Something similar would need to happen in `VerifiedOperation` too.

Slight less clear for me is what ha[[ens on the client side during operation construction, for example, are clients aware of this option to omit `previous_operations` or is it something that just happens in the background? For example, in `sign_and_encode()` when `previous_operations = backlink` could they simply be removed?

This has the effect of tying together operations and their entries more than they are currently (although an operation cannot exist without it's entry anyway, so I suppose this separation is not really there in the first place), not sure if this is a problem.

**Comment by sandreae** [comment]
Side note: I think an interesting side-effect would be that we could enforce single-writer operations in the cddl definitions (for say, system schema which will only be single writer). If any operation of this type arrives at a node _with_ `previous_operations` it could be rejected. I'm not sure how often this would happen, but it would seem to close off one way "invalid" operations can be published to nodes....

**Comment by adzialocha** [comment]
I'm closing this here, as we have the regarding issues already in the handbook (and it is a spec-discussion anyhow).
