### ISSUE TITLE
Make resolver generic so it can be implemented by different schemas

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#210]
See sketches here: https://gist.github.com/sandreae/84d29d8b20fc963b7b117fb4ca5191f2

**Comment by sandreae** [comment]
Looking into this, I actually don't think we need anything this involved yet. If all the system schema we need immediately (Schema, SchemaField) are being materialised using the same resolution pattern as regular application schema, then I'm not sure what changes are needed. If we want a specialist "SchemaField" type for example, we can implement a conversion trait `let schema_field: SchemaField = document.try_into()` or something else simple for now.

**Comment by adzialocha** [comment]
> Looking into this, I actually don't think we need anything this involved yet.

Good point. We shouldn't implement it if we don't need it (yet). I can see how this might be useful sometime, but lets look into it when we get there®

**Comment by adzialocha** [comment]
I've kept this issue here for the future and created a new one for the milestone? https://github.com/p2panda/p2panda/issues/220 Does this make sense?

**Comment by sandreae** [comment]
> Does this make sense?

yeeees, much sense :+1:

**Comment by adzialocha** [comment]
As it looks right now this might not be the required pattern anymore if I see this right? In that case we can close this issue here.

I like the idea of keeping materialization "low-level" meaning that _any_ operation results in _some_ document view after materialization. The conversion into something more "high level" with additional semantics happens somewhere else (for example in conversion traits as we already do it for "Schema" and "Schema Field" views).

**Comment by cafca** [comment]
I agree! @sandreae feel free to reopen otherwise.
