### ISSUE TITLE
Specify schema hash for application schemas

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#211]
So far we derive the schema hash from the first entry of a application schema document, how do we do this for system schemas?

Some options we have:

1. Use schema field to also mention some enum value like key_group_v1 instead
2. Just generate a random hash and assign it "forever" to certain system schemas
3. Use funny hashes like 0000000000...000001 or babb1ed.. and assign them forever
4. Publish schemas actually on p2panda (and the bytes of the entries / payloads in a public repository) with the system schema definitions inside. Take the hash from there and assign them forever (this does NOT mean that one needs to materialize system schemas before, they are still hardcoded), its only the symbolic act of "where did the hash come from", thats all
5. New and hot: Introduce a `type` field (similar as option 1, just separated)

**Comment by sandreae** [comment]
I like option 1) too.

**Comment by adzialocha** [comment]
Let's go for 1 then!

**Comment by sandreae** [comment]
Hmmm...... I just looked at implementing this. I'm not so sure about option 1 anymore.... It feels like it might be adding unnecessary checking and de/serializing complexity in many places. Somehow I quite like option 3 or 4 now.....

**Comment by sandreae** [comment]
We could still have an enum with option 3 or 4, checking for known system schema hashes and serdering (:wink:) correctly, but that way we still end up with a valid hash. That's quite nice.

**Comment by sandreae** [comment]
Something like this: https://gist.github.com/sandreae/5417338975841ed1880c2e69cc00d0c3

**Comment by sandreae** [comment]
or is it pointless doing both :thinking: ..............

**Comment by sandreae** [comment]
> But wouldn't it work now if you replace the hashes (0x0000..) with human readable values like "schema" and "schema_fields"?

Yeh, that would work, it seemed strange that sometimes a `SchemaType` was represented by a strict hash string, and sometimes it was represented by.... not a hash string..... With the above then we can coerce all schema types into hashes if we like. And the strings would pass the same string validation when serialized.

**Comment by sandreae** [comment]
WIP PR: https://github.com/p2panda/p2panda/pull/221

**Comment by adzialocha** [comment]
Nice pages around hexspeak:

https://en.wikipedia.org/wiki/Hexspeak
https://reminiscential.wordpress.com/2008/09/03/hexspeak-word-list/

**Comment by cafca** [comment]
We had a bit of a discussion on this topic on Monday where we talked -among other things- about representing schemas as relations. One thing that I don't like so much about the approach in #221 is all the zeroes (so many zeroes).

If we plan on representing application schemas as relations I see no reason to step away from the strict 68 byte length for system schema identifiers so I would suggest going back to option 1 :D

**Comment by adzialocha** [comment]
> If we plan on representing application schemas as relations I see no reason to step away from the strict 68 byte length for system schema identifiers so I would suggest going back to option 1 :D

Agreed! I'm also for Option 1 :+1:

**Comment by sandreae** [comment]
Me too!! 👍 I like option 1 best now.

**Comment by sandreae** [comment]
Need to check out the new relation format.

**Comment by adzialocha** [comment]
How about snake_case then? Like `schema` and `schema_field` and `key_group` etc.

**Comment by sandreae** [comment]
That's what I imagined.

**Comment by cafca** [comment]
> How about snake_case then? Like `schema_v1` and `schema_field_v1` and `key_group_v1` etc.
> 
> Related to: #213

Looking at the draft key group spec we would then have field schemas with names like [`key_group_membership_request_key_group_v1`](https://github.com/p2panda/handbook/pull/118/files#diff-815baa9110659374221c20d2c1a585c96e00f18330e7ab2a87ac98cd24feb9d3R54) but I guess that's alright. It's complex anyway.

**Comment by cafca** [comment]
So we decided on option 1! Closing this now.

**Comment by cafca** [comment]
Actually, I should have closed this with a change to the handbook .___.

**Comment by sandreae** [comment]
Ah, I just made this change and went for `SCREAMING_SNAKE_CASE`

**Comment by sandreae** [comment]
Shall I change it to `not_screaming_snake_case`?

**Comment by sandreae** [comment]
I changed it to non screamy, nobody wants to be screamed at....
