### ISSUE TITLE
Fix letter casing in operation encoding

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#213]
This is an operation represented as JSON:

```json
{
  "action": "update",
  "schema": "0020c65567ae37efea293e34a9c7d13f8f2bf23dbdc3b5c7b9ab46293111c48fc78b",
  "version": 1,
  "previousOperations": [
    "0020e2938c68b983e2985fa1fb9f23baec33bdadc3001990445589c17b43bb3625e3"
  ],
  "fields": {
    "age": {
      "type": "int",
      "value": 28
    },
    "height": {
      "type": "float",
      "value": 3.5
    },
    "is_admin": {
      "type": "bool",
      "value": false
    },
    "my_friends": {
      "type": "relation_list",
      "value": [
        {
          "document": "0020c7443358100c7358afcc9441157635cd3512e416e4eb412f60be43c21c5f5e16",
          "document_view": [
            "0020189e54c15e3f091475a7a6fee9bef1f7d9ac08643ee968fe100e673ecff95e3a"
          ]
        },
        {
          "document": "0020cd55e614479f41413c3c6de32d21c8ace85c22a86c0c3bd27450d65dc4e6d6c2",
          "document_view": []
        }
      ]
    },
    "profile_picture": {
      "type": "relation",
      "value": {
        "document": "0020ea32666fbc6f54d2dc8528fed3621be1d4c9084dabc5d10e20a4da3552e5b76c",
        "document_view": []
      }
    },
    "username": {
      "type": "str",
      "value": "bubu"
    }
  }
}
```

`previousOperation` is written in camelCase but everything else is snake_case (`relation_list` for example).

1. Let's check if there is a CBOR convention for letter casing of names
2. If not: Lets decide what to do in JSON (wasm) and in CBOR world!
3. ... aaand if its different how can we solve this?

**Comment by cafca** [comment]
I would like to rename `previousOperations` anyway because technically all other operations in the same document are "previous operations". Some options:

- `dependencies`
- `document_tips`
- `merge_on` or something else like `merge_X`
- `document_view`

Maybe there's other options as well.

**Comment by sandreae** [comment]
Is it a...... `relation` ? :rofl:

**Comment by sandreae** [comment]
(everything is now a relation)

**Comment by adzialocha** [comment]
This discussion seems to be better here: https://github.com/p2panda/p2panda/issues/204

This issue is about the letter casing :judge:

**Comment by adzialocha** [comment]
I could not find a "recommendation" for CBOR (guess its just a binary encoding format over "everything").

I would be in favor of writing everything in `snake_case` and I can't really tell why :rofl: Maybe because almost everything is already like this? To translate to JavaScript and back we can still convert the casing (we already do this partly).
