### ISSUE TITLE
Implement `Schema` struct

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#215]
A cool new thing which holds: `name`, `description` and `fields`.

Sketch by Sam: https://laub.liebechaos.org/Xol8rqMjQWG04Ct6DaaiRw#

**Comment by adzialocha** [comment]
Do we need a `SchemaField` struct?

**Comment by sandreae** [comment]
Been looking a little into this. We talked about using new type pattern like so:

`struct Schema(DocumentView);`

Which is cool! But then I wonder about validation (as always :roll_eyes:) within `p2panda-rs`. If `Schema` is "just" a wrapper around document view, then on a node, validation should have happened when resolving the document (the schema hash is stated, operations are validated, we know it actually is a schema) but this isn't apparent in `p2panda-rs` and it feels very weird just to assume the fields in the wrapped `DocumentView` are correct.

I can see a few ways forward:

A) actually use the system schema cbor definition to validate the DocumentView (which itself is almost just a wrapper around `OperationFields`) bytes?
B) implement `TryFrom<DocumentView for Schema>` and then validate we have the correct fields.
C) Just do without these types completely :rofl: they are only document views anyway, an implementation knows the schema of the document it is resolving and performs appropriate validation in any case.

If we do "B" then it makes me wonder if we may as well be creating a richer `Schema` struct...

What do you think?

**Comment by sandreae** [comment]
Ok, great, this is roughly where I ended up too. I can make some sketches :+1:

I kept tripping up on "Cool, everything is a document view, let's make thin wrappers and move on" .... later.... "Ok, let me just get my `Schema` which knows about things like fields and types and whatnot and looks a certain way.... oh....."

**Comment by sandreae** [comment]
In progress here: https://github.com/p2panda/p2panda/pull/250
