### ISSUE TITLE
Convert materialized application documents into specialized system documents

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#220]
All the system schema we need (Schema, SchemaField) are being materialised using the same resolution pattern as regular application schema. When we want a specialist SchemaField or Schema type, we could use a conversion trait:

```
let schema: Schema = document.try_into()?
```

...or something else for now.

Related discussion: https://github.com/p2panda/p2panda/issues/210

**Comment by sandreae** [comment]
WIP: https://github.com/p2panda/p2panda/pull/226

**Comment by sandreae** [comment]
related convo: https://github.com/p2panda/p2panda/issues/215
