### ISSUE TITLE
warning: unused manifest key: bench.0.html_reports

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#224]
I receive the message: `warning: unused manifest key: bench.0.html_reports` every time I run `cargo run` or `cargo test`. When I remove the regarding entry in `Cargo.toml` under `[[benches]]` it disappears, but do I break something then?

Ping @sandreae, maybe you know what to do?

**Comment by adzialocha** [comment]
> what happens if you run cargo bench (except for you getting bored as loads of benchmark tests run)?

Just tried it, the warning stays :cry:

**Comment by cafca** [comment]
and it stores performance measurements in cbor, hehe

**Comment by sandreae** [comment]
Great we have more benchmarks now toooo!!!
