### ISSUE TITLE
Warning about `unused manifest key: bench.0.html_reports`

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#237]
Several Cargo commands, for example `cargo check` give me

```
warning: unused manifest key: bench.0.html_reports
```

since we added the `[[bench]]` section in `Cargo.toml`.

**Comment by adzialocha** [comment]
Duplicate of: https://github.com/p2panda/p2panda/issues/224 :-)

**Comment by cafca** [comment]
oof
