### ISSUE TITLE
Validation when converting `DocumentView` into specialised `SchemaView`

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#238]
What behaviour do we expect when trying to parse an application `DocumentView` which follows an application schema, but contains the compulsory key-values as a system schema, into a specialised `SchemaView` or `SchemaFieldView`?

Should:  
```
farm {
  name: String,
  description: String,
  fields: RelationList,
  animals: RelationList
}
```

be allowed to be coerced into a `SchemaView`?

**Comment by adzialocha** [comment]
Is this related? https://github.com/p2panda/p2panda/issues/242

**Comment by sandreae** [comment]
Yeh, it is related, but not exactly the same issue. 

I suppose I just don't see how allowing invalid type coercion is desirable, especially when it's very easy to stop it.

When is the case where we expect the above example to be parsed into a `SchemaView`? (I don't think there is a case, right?).

**Comment by sandreae** [comment]
Ah, ok, maybe I spot the reason this is causing some mental challenge.

Currently we lose `Schema` information when creating `DocumentViews` so we can't just check if the schema is `schema_v1` or `schema_field_v1`.

**Comment by sandreae** [comment]
So we end up converting just a map of values (which were validated against a schema during `Document` building, but that information is gone now).

**Comment by adzialocha** [comment]
Is there a "meta" construct we can introduce which spits out a `Schema` in the end and internally uses the materializer after validating the data? Then it might not be so bad that the "DocumentViews" don't know about the schema, because the overall procedure knows what it is dealing with?

I hope I could bring that point across, not sure how to put it in better words right now :-D

**Comment by sandreae** [comment]
Yeh, I think I get you.

I feel like we are heading back to `DocumentBuilder` throwing out the correct document view already, depending on the schema. I think this could be implemented quite neatly without too many changes. 

Does that match your thought?

**Comment by sandreae** [comment]
Ah, sorry, maybe that doesn't quite match, as you're taking about `Schema`....

**Comment by sandreae** [comment]
I mean, we know all operations have been validated on arrival against their schema though, so maybe I'm just being really psycho here......

**Comment by sandreae** [comment]
(please tell me if I am)

**Comment by adzialocha** [comment]
> I mean, we know all operations have been validated on arrival against their schema though, so maybe I'm just being really psycho here......

Haha, you're not a psycho lol, but indeed thats quite a good point with the validation via CDDL beforehands ..

**Comment by sandreae** [comment]
I guess we're not talking about the internal validity of the schema (the above example is a valid DocumentView), it's just how we deal with cases where a valid DocumentView is incorrectly parsed into a valid SchemaView (and if this can happen).

**Comment by adzialocha** [comment]
> I guess we're not talking about the internal validity of the view (the above example is a valid DocumentView), it's just how we deal with cases where a valid DocumentView is incorrectly parsed into a valid SchemaView (and if this can even happen).

This is how I understand it as well .. I think if one declares the materializer as something which needs validation of the operations beforehands we should be fine from here. I can imagine that there is actually much more which would go wrong if we would not have CDDL beforehands.

Probably all of this is related to the great "Validation" jam, finding out what, how and when we validate what?

**Comment by sandreae** [comment]
This would be one approach https://github.com/p2panda/p2panda/pull/257

**Comment by sandreae** [comment]
Now a documents view is converted into is more specific form during building.

**Comment by adzialocha** [comment]
> I like it, but I can't quite grok what impact it has down the line (how we interact with document views in `aquadoggo`) but my feeling is that it actually saves us some work later, or at the very least, makes explicit the fact that document views have a variety of forms.

That's tricky in general, I also have this often. If we feel like that I think it's a good idea to use it in aquadoggo first to learn about the API.

Though, if you like it, that's also good already! 🤣

To me it also looks good!

**Comment by sandreae** [comment]
I think I'll move this issue out of the milestone for now as I don't think we can solve it until later :+1:

**Comment by adzialocha** [comment]
This one is a similar ticket but concerning _all_ methods which are somewhat related to creating schemas or deriving data from it (like operations): https://github.com/p2panda/p2panda/issues/426
