### ISSUE TITLE
Create Typescript declarations with build

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#24]
- [ ] Create a single `index.d.ts` in the build folder with types for the exported module
- [ ] No import paths in the declaration that don't resolve independent of the p2panda repository
- [ ] Unset env var in `npm run test` that disables type checks

**Comment by adzialocha** [comment]
Creating a single automated definition file seems to be tricky, I found a few experimental webpack plugins (https://github.com/eliraz-refael/dts-webpack-bundler) but they were all not working.

**Comment by adzialocha** [comment]
I remember you had a simple solution for this in the end @cafca (as all the others seemed very complicated), but I can't find it in the code-base. Did we merge it in the end or is this still pending?

It could be nice to have it in for the next release (with our nice and shiny new API) :smile:
