### ISSUE TITLE
Revisit visibility of `DocumentView` constructor

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#242]
The fact it's possible to pass in any combination of `DocumentViewId`, `DocumentId` and `view` seems quite haphazard. Should we make sure these structs are all private to the document construction process (where the validation occurs)?

Related discussion: https://github.com/p2panda/p2panda/pull/235#discussion_r816777477

**Comment by cafca** [comment]
I don't see a reason not to just make `DocumentView::new` `pub(crate)` right now? It's not required outside of testing because you get `DocumentView` instances by first creating a document and then retrieving a view from there.
