### ISSUE TITLE
Rename `Relation` and `PinnedRelation` to `DocumentRelation` and `DocumentViewRelation`

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#247]

**Comment by sandreae** [comment]
I don't think I support this change anymore... i quite like it as it is :grimacing: how do we all feel, any changes?

**Comment by sandreae** [comment]
98.888% of the time people will only want to use `Relation`, they won't need to know anything about "pinned", "document views" or anything, in this case `Relation` says all you need to know. And in the special case, "pinned" is also very clear (even if you don't know about document views).

**Comment by cafca** [comment]
I also like that _pinning_ is such a physical metaphor

**Comment by sandreae** [comment]
Yeh, me too!

**Comment by sandreae** [comment]
Shall we close this then? I don't think @adzialocha ever wanted to change it.
