### ISSUE TITLE
Make `p2panda-js` and `p2panda-rs` stateless?

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#253]
`p2panda-rs` in itself is currently designed as a stateless framework. Storage and state is something developers need to implement on top of it (we do it in `aquadoggo` and in our mocked node / client implementations). In `p2panda-js` it is slightly different, there we already have a notion of an external data provider (making requests) and a little bit of caching. Also, in `p2panda-js` we have a more "wrapper" sort of API.

Obviously to build an application on top of p2panda one needs state so the question is now where to draw the borders. Also the idea of having some sort of storage notion in `p2panda-rs` is coming up (https://github.com/p2panda/p2panda/issues/223) but it feels like a fairly large refactoring with potentially ugly API outcomes. 

Random thoughts:

* Remove all state and higher-level API from `p2panda-js`, make it as "agnostic" and low-level as `p2panda-rs`, mostly just being a simple wrapper around the WebAssembly exports
* Trying to get it to the same feature-set as `p2panda-rs` (so one could imagine building an JavaScript Node implementation one day with it)
* Stateful things will be implemented in form of a new framework, in a new repository, like a more high-level Rust and JavaScript library using `p2panda-js` and `p2panda-rs` internally. For now it could be as simple as moving everything we currently have in `p2panda-js` into this new repository
* `p2panda-js` and `p2panda-rs` become the "core" libraries. The new things are on top of that, providing everything you need to build a) a client b) a node - in both programming languages
* Storage providers can still be abstract in these high-level frameworks, in Rust we can express it in traits, in JavaScript there are surely some similarly nice API patterns we can use
* The code-bases don't get to crammed with different purposes, we work on "core specification" stuff in the core libraries and everything else happens somewhere else: State, Storage, Networking, Caching, etc.
* We don't need to refactor a lot of code to introduce storage anymore, `p2panda-rs` can stay the same, the new library will build on top of it

**Comment by adzialocha** [comment]
With storage traits we could refactor p2panda to consist of 3 types of packages / crates:

1. core functionality (stateless) `p2panda-rs`
2. trait definitions `p2panda-traits`
3. framework to build clients / nodes with (including networking, storage implementations, etc.) `aquadoggo` or `shushek` or other funny names we can come up with

**Comment by adzialocha** [comment]
Thoughts on why it might be nice to separate it:

* Separation of concerns, it gets very clear what a code-base should do and not should do
* Less code
* Less dependencies
* Easier to grok what you're dealing with

Some of these things can also be achieved with restructuring the folders (for example introducing a `core` module) and introducing feature flags instead of separating it into multiple crates. I'd be also up for exploring that direction as well!

**Comment by cafca** [comment]
I think I'm warming up to the idea of introducing more libraries where code is placed. We are adding a lot of stuff right now and there's even more to come.
