### ISSUE TITLE
Support all `Relation` types everywhere?

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#258]
Just realised that I think we implemented all `Relation` variants on `OperationValue` but we don't actually support this everywhere. Eg. in the CDDL generator where only document relations were supported.  Think this is related to pending work in `js` world too. But I think it's worth checking what we intend for this before finishing the `Schema` milestone. 

Questions:
- do we want to support all relation types in application schema?
- if "yes", do we actually support this ;-p

**Comment by adzialocha** [comment]
This is related: https://github.com/p2panda/handbook/issues/157

**Comment by sandreae** [comment]
Oof, sorry, somehow I didn't see that issue!

**Comment by adzialocha** [comment]
> Oof, sorry, somehow I didn't see that issue!

No problem, it's just hidden somewhere else 😅

**Comment by adzialocha** [comment]
> Just realised that I think we implemented all Relation variants on OperationValue but we don't actually support this everywhere.

Yes, I think currently we support all of them in `OperationValue` (Rust API) and in the WebAssembly API.

> Eg. in the CDDL generator where only document relations were supported. Think this is related to pending work in js world too.

Not sure if `p2panda-js` work and the CDDL generator are related, but yes, in both of them all relation possibilities are not implemented yet. The ticket for `p2anda-js` is here: https://github.com/p2panda/p2panda/issues/244 :+1:
