### ISSUE TITLE
Unique string identifier for application schemas

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#267]
Should we have a convention for representing all `SchemaId` variants as strings? This would make it nice and easy to store them all in a db.

For system schema this is easy, they are already defined as strings `schema_v1` and `schema_field_v1` (both these are deprecated terms though ;-p)

For application schema which contain an array of hashes (document view / pinned relation) it needs more though

## Options
- concat the array of hashes into something like `0A00_0B00_0C00`
- hash the array of hashes (then use this as an id for the list of hashes which are stored in their own table)

**Comment by adzialocha** [comment]
> hash the array of hashes (then use this as an id for the list of hashes which are stored in their own table)

I like this! This is close to https://github.com/p2panda/handbook/issues/151

**Comment by sandreae** [comment]
Yeh, that's where I got the idea :rofl:

**Comment by sandreae** [comment]
> DocumentViewHash
:heart:

**Comment by cafca** [comment]
I would also add the schema name into that string representation, so something like

`venue_11df58403d1802597484f5cd862fef21164135d2508ac9b494c4d32b`

**Comment by cafca** [comment]
I had a go at this but it seems to me like adding the schema name as I suggest makes this a bit more involved.

**Comment by sandreae** [comment]
Hey hey! I need to recap on the purpose of this issue, I think I forgot where the string idea came from for me :rofl:

- in `aquadoggo` uperations arrive and they have a `SchemaId`
- for system schema, this id is a string
- for application schema this id is an array of hashes
- we need to deal with both cases
- one idea is to hash the array of hashes ;-p to get a `HashId` string
- store this in the db
- _also_ store all the original id hashes (from the `SchemaId` array) and relate them to the `HashId`

This was my original thinking on the use of the string id I think, hope this makes sense!

**Comment by sandreae** [comment]
(@cafca hehe, saw your comment pop up while I was typing)

**Comment by sandreae** [comment]
I don't think my comment conflicts with the change of thinking towards `Schema` creating these ids :+`:

**Comment by sandreae** [comment]
Also, I wondered if there are other places where the same pattern is needed, need to think that through a bit more though.

**Comment by adzialocha** [comment]
> Hey hey! I need to recap on the purpose of this issue, I think I forgot where the string idea came from for me rofl

This resembles my mental model as well I think :+1:

**Comment by adzialocha** [comment]
For the confused ones (including me): This issue is about defining an unique name for schemas for example to use this as a sql table.

This is somewhat related but touches upon much more specification: https://github.com/p2panda/handbook/issues/160

**Comment by adzialocha** [comment]
Zeitgeist
