### ISSUE TITLE
Untagged serialisation of operation fields

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#291]

**Comment by cafca** [comment]
I looked into this a little and didnt really find a way to pass additional information (the schema) into serde to inform deserialisation. do you know of a way to do that?

**Comment by adzialocha** [comment]
> I looked into this a little and didnt really find a way to pass additional information (the schema) into serde to inform deserialisation. do you know of a way to do that?

Maybe we need an intermediate type which contains both the `Schema` and the `OperationEncoded`. During deserialization / serialization one has access to that object and can retreive all the information needed.

With deserialization one can also use the `Visitor` pattern, I think you can create a custom Visitor which also contains the `Schema`, you will then get access to that during the process, but I'm not sure how that works for serialization, maybe it can be a similar process.

**Comment by cafca** [comment]
There's an easy way to get most of the way.

```rust
#[serde(tag = "type", content = "value")] // <-- removing this line
pub enum OperationValue {
```

Then we go from

```json
{
  "action": "create",
  "schema": "chat_0020c65567ae37efea293e34a9c7d13f8f2bf23dbdc3b5c7b9ab46293111c48fc78b",
  "version": 1,
  "fields": {
    "message": {
      "type: "str",
      "value": "Ohh, my first message!"
    }
  }
}
```

to 

```json
{
  "action": "create",
  "schema": "chat_0020c65567ae37efea293e34a9c7d13f8f2bf23dbdc3b5c7b9ab46293111c48fc78b",
  "version": 1,
  "fields": {
    "message": {
      "str": "Ohh, my first message!"
    }
  }
}
```

This is already saving a lot of redundant bytes compared with what we have now and the only thing we need to change is the marshalling helper in Javascript. If we find a way to build completely untagged serialisation before `v1` that would be great of course. However, this is something we can have now. I will put up a draft PR for you to check out if you'd like.

**Comment by adzialocha** [comment]
I'm not sure I like that version more than what we have, it's somewhat hacky to have that level of nesting now? I'd rather would go for "the real thing" than doing this.

We don't save a breaking operation version change anyhow with this approach and the original version just feels fine, verbose but easy to read.

**Comment by cafca** [comment]
Hmm, for me this is not hacky at all, even a bit easier to read actually. @sandreae how do you feel?

**Comment by cafca** [comment]
I would also still prefer the original idea a lot! I just couldn't find a way to do it when I last tried (using the Visitor trait you mentioned).

For me this is about our credo of being data-efficient. Some operations from our test-data are 10% smaller even with this change so I think it would be nice to make an improvement like that before making a stable release. For me personally this is still fine to read but if you all think it would be more developer-friendly to stay with the serialisation tagging we have now then maybe that's worth saving some bytes. It's just that we will have a lot of operations so even a couple of bytes can make quite a difference.

**Comment by adzialocha** [comment]
Thank you for this! It makes sense 👍

> I would also still prefer the original idea a lot! I just couldn't find a way to do it when I last tried (using the Visitor trait you mentioned).

Should we have a go on this together? Maybe we can find a solution. 🤓

**Comment by adzialocha** [comment]
This could be a way:

```rust
use std::collections::HashMap;

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
struct RawOperationFields(HashMap<String, RawOperationValue>);

#[derive(Serialize, Deserialize, Debug)]
#[serde(untagged)]
enum RawOperationValue {
    String(String),
    Integer(usize),
}

#[derive(Debug)]
enum OperationValue {
    String(String),
    Relation(String),
    Integer(usize),
}

#[derive(Debug)]
struct Operation(HashMap<String, OperationValue>);

#[derive(Debug)]
struct Schema(HashMap<String, String>);

impl Schema {
    pub fn new(fields: Vec<(String, String)>) -> Self {
        let mut map = HashMap::new();
        for item in fields {
            map.insert(item.0, item.1);
        }
        Self(map)
    }
}

fn parse(schema: Schema, fields: RawOperationFields) -> Operation {
    let mut map = HashMap::new();

    for (field_name, value) in &fields.0 {
        let field_type = schema.0.get(field_name).expect("Field not in schema");

        let field_value = match field_type.as_str() {
            "str" => match value {
                RawOperationValue::String(str) => OperationValue::String(str.to_owned()),
                _ => {
                    panic!("Needs to be a string")
                }
            },
            "relation" => match value {
                RawOperationValue::String(str) => OperationValue::Relation(str.to_owned()),
                _ => {
                    panic!("Needs to be a string")
                }
            },
            "number" => match value {
                RawOperationValue::Integer(num) => OperationValue::Integer(*num),
                _ => {
                    panic!("Needs to be a number")
                }
            },
            _ => {
                panic!("Unknown type!")
            }
        };

        map.insert(field_name.to_owned(), field_value);
    }

    Operation(map)
}

fn main() {
    // 1. Define a schema
    let schema = Schema::new(vec![
        ("name".into(), "str".into()),
        ("stuff".into(), "relation".into()),
        ("age".into(), "number".into()),
    ]);

    // 2. Some data which needs to be deserialized
    let data = r#"
        {
            "name": "Panda Schmanda",
            "stuff": "pinned_relation(0020)",
            "age": 32
        }
    "#;

    // 3. First, deserialize it into "raw" operation types
    let fields: RawOperationFields = serde_json::from_str(data).unwrap();

    // 4. Then, translate it into a "checked" operation with the help of the schema
    let thingy = parse(schema, fields);

    // Here it is!
    println!("{:?}", thingy);
}
```

**Comment by adzialocha** [comment]
I assigned myself to this issue @cafca as I thought it will be done from scratch and all the other issues you already have some progress on?
