### ISSUE TITLE
Implement new specification for `publish_entry` and `next_entry_args`

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#301]
When implementing `StorageProvider` in #274 we noticed it was worth looking over our default implementations (brought over from `aquadoggo` world). Some errors look suspiciously un-throwable, and maybe we want to do some refactoring (if not, that's also cool).

**Comment by sandreae** [comment]
To resolve this issue we will take the following steps in `aquadoggo`:
- implement the newly specified validation flows for the two API endpoints `publish_entry` and `next_entry_args` defined here: https://whimsical.com/api-validation-4X53TdGvPLFUtmuBFvriW5
- create a new `validation.rs` module where we break out reusable validation methods which likely use the `store` internally
- No longer use `publish_entry` and `next_entry_args` on `StorageProvider` in favour of our own more modular implementation

Later we will likely remove `publish_entry` and `next_entry_args` from the store in `p2panda-rs` as well. These are higher level API methods which would more happily live elsewhere.

**Comment by sandreae** [comment]
I'm assigning this to myself as I've already started it :+1:

**Comment by adzialocha** [comment]
> I'm assigning this to myself as I've already started it :+1:

Cool, let us know how it feels to go in that direction 👍

**Comment by sandreae** [comment]
It feels goooooooood.

**Comment by sandreae** [comment]
Implemented here: https://github.com/p2panda/aquadoggo/pull/204
