### ISSUE TITLE
Storage methods for replication

### ISSUE THREAD

**Issue by pietgeursen** [p2panda/p2panda#309]
Yo,
I think I need another method to help me with replication. 

Something like:

```rs
async fn get_next_n_entries_after_seq(author_id: Author, log_id: LogId, seq_num: SeqNum, max_number_of_entries: usize) -> Result<Option<Vec<StorageEntry>>>
```

With this I think I should be able to expose a gql method that is paginated. My replication code will manage the cursor and decide what the value of `max_number_of_entries` will be.

I'm not sure if it belongs in the `entry_store` or the `storage_provider` or somewhere new. What do you think @sandreae?

**Comment by sandreae** [comment]
Nice, thanks for flagging this, I'm sketching out what is needed next for the store in general here right now: https://laub.liebechaos.org/TQPRKUS4TbG0iuk28ABfwg?edit and will be working making additions today.

> With this I think I should be able to expose a gql method that is paginated. My replication code will manage the cursor and decide what the value of max_number_of_entries will be.

Fantastic, that's a big help, I have quite a lot on my plate right now ;-p

> I'm not sure if it belongs 

It's nice having responsibilities seperated out into their own stores (`EntryStore`, `LogStore`, `OperationStore` etc...) but it is super hard to know where some things should go :rofl:

**Comment by pietgeursen** [comment]
> Fantastic, that's a big help, I have quite a lot on my plate right now ;-p

Are you ok picking this piece up or should I make a PR for it? Totally fine if you're too busy.

**Comment by sandreae** [comment]
No, it's totally fine, this is what I'm busy with 👍

**Comment by pietgeursen** [comment]
Oh, I just thought of another one:

I'm guessing we have a use case for asking for an `Entry` plus its chain of lipmaa links. 

I think we might want something like:

```rs
async fn get_all_lipmaa_entries_for_entry(author_id: Author, log_id: LogId, seq_num: SeqNum) -> Result<Option<Vec<StorageEntry>>>
```

Open to finding a better method name btw.

Which would start at `seq_num`, calculate the lipmaa links back to `seq_num` 1 and then get those entries from the db all in one go.

**Comment by sandreae** [comment]
Niiice, thanks!

(I am open to not finding a better name :rofl:)

**Comment by sandreae** [comment]
Ok, I started a PR for all these changes here: https://github.com/p2panda/p2panda/pull/310

**Comment by sandreae** [comment]
They will still need to be implemented in `aquadoggo`, but so far that means only `get_entry_by_hash` as the others have default (if somewhat inefficient) implementations defined.

**Comment by sandreae** [comment]
You could switch over to this branch in your `aquadoggo` PR if you like, it would like to merge it quick, but it does touch on some fairly low level things so probs others would like to at least skim it.
