### ISSUE TITLE
Make `previous_operations` a `DocumentViewId`  

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#315]
It would be useful to have a little more tooling around `previous_operations`. Right now I'd like to be able to parse it from a string. Currently it is represented as a list of operation ids `Option<Vec<OperationId>>` but maybe it could have it's own type, or we use `DocumentViewId` here? This makes sense to me conceptually (prev_ops are pointing at a document view). This would also provide the tooling I need.

**Comment by adzialocha** [comment]
I'd be up for using `DocumentViewId` here! I remember you had a point against it once in the past, what was it again?

**Comment by sandreae** [comment]
Hmmm, I can't think of any reason.... Maybe I had one in the past 😂

 Using 'DocumentViewId` would also give meaning to having previous operations as an optional field.

**Comment by cafca** [comment]
If I remember correctly it was that you felt that `previous_operations` is a property of a single graph node while `DocumentView` is a descriptor for constructing a whole graph.

**Comment by sandreae** [comment]
Haha, you're right, I think that is what I felt, yeh.... But! I want more tooling around prev ops (like in and out of strings and other stuff document view has), so it does make sense to borrow them. We could wrap it?

**Comment by cafca** [comment]
I think there's not even a conflict between these perspectives necessarily. `previous_operations` is a property of a graph node, yes, and this property allow reconstructing the graph how it was before that node was added - that's a `DocumentViewId`!

**Comment by sandreae** [comment]
Yeh, now I really like that those two things are the same "thing".

I wasn't suggesting changing the field name right now (though, not really against that if there is a desire), so it would look like:

```
Operation {
  ...
  pervious_operations: DocumentViewId,
  ...
}
```
