### ISSUE TITLE
Implement `std::hash::Hash` for entry and operation

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#32]
There's some possible alternatives, see discussion [here](https://github.com/p2panda/p2panda/pull/23#discussion_r572798384)

**Comment by sandreae** [comment]
Bumping this issue. I'll try by implementing the `Hash` trait for our own hash struct and see if this can then be returned for similar implementations on `Operation` and `EntrySigned`. 

A different approach would be needed to for `Entry`, but let's see.
