### ISSUE TITLE
Consistent string slice return type for `as_str` methods

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#327]
Make sure that `as_str` methods return a string slice and, if the method requires allocating new memory for the return value, name that method `serialise` instead.

# Rationale

The `as_str()` method returns a string slice by convention. However, some of our `as_str` implementations return `String`. Now we could just add `to_string` methods that return `String`, but Rust style (Clippy) wants us to to implement `Display` instead of just having `to_string` methods. In the past we decided to call String-returning methods `serialise` instead (in https://github.com/p2panda/p2panda/pull/269/). Personally, I would rather disregard the Clippy rule and use the `to_string` name but I think between us there was some disagreement about that and we settled on `serialise`.

e.g.

```rust
pub fn serialise(&self) -> String {...}

pub fn as_str(&self) -> &str {...}
```

**Comment by adzialocha** [comment]
That's maybe helpful: https://loige.co/how-to-to-string-in-rust/

**Comment by adzialocha** [comment]
I've stumbled now a couple of times over implementation bugs (could discover them through tests, but otherwise unnoticed), where I accidentally used `to_string` and that led to an invalid hash .. Is there a way to decouple the short string methods even more? I understand they have a nice logging benefit, but I'm afraid it might also be a source of many bugs which are hard to track down.

**Comment by adzialocha** [comment]
> I've stumbled now a couple of times over implementation bugs (could discover them through tests, but otherwise unnoticed), where I accidentally used `to_string` and that led to an invalid hash .. Is there a way to decouple the short string methods even more? I understand they have a nice logging benefit, but I'm afraid it might also be a source of many bugs which are hard to track down.

Meh, but it doesn't really make sense with how Rust wants it to be 😥

This is another resource on that topic: https://github.com/rust-lang/rfcs/blob/master/text/0565-show-string-guidelines.md#user-facing-fmtdisplay

At the end they talk about an "adapter pattern" which looks interesting?
