### ISSUE TITLE
Batch publishing entries

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#330]
Clients would probably like to publish entries without always asking the node for the next entry arguments _plus_ making a publish request for each item

**Comment by cafca** [comment]
This issue is in the p2panda repo but I assume that it's enough for us to implement this in aquadoggo, would you mind moving it @adzialocha?

**Comment by adzialocha** [comment]
> This issue is in the p2panda repo but I assume that it's enough for us to implement this in aquadoggo, would you mind moving it @adzialocha?

It was defined here for the storage traits :+1: but I guess this can be closed now as we can do everything in our fancy GraphQL API :sparkles:
