### ISSUE TITLE
Cycles in recursive relations?

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#348]
Should we be worried about (EDIT: cycles in) recursive relations?

**Comment by adzialocha** [comment]
> I thought about in the dependency task 

Yes, that will be the same, it will not spawn anything new and interrupt the cycle as soon as there is nothing to do (like a recursive function stopping when some condition was fulfilled):

![Screen Shot 2022-06-08 at 17 55 05](https://user-images.githubusercontent.com/1822473/172662679-f205bf84-2fe4-4eee-b2fb-f6dfd951aadf.png)

> database queries

Not sure what you mean by that but I assume it has something to do with your fancy recursive query in SQL :-D I'm not sure if thats a problem, but in any case it might also not be necessary. I can remember we could proof some weeks ago that there is no need to recurse through all relations as the task logic figures that out. It is enough to retreive only the documents of the next hop in the document dependency graph.

**Comment by adzialocha** [comment]
The dependency task is the recursive function itself basically. It spawns itself as soon as it sees the need to go deeper!
