### ISSUE TITLE
Running `cargo test` fails when not all features are enabled

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#349]
Running `cargo test` in main fails when not all features are enabled (`cargo test --all-features`). Is there a way to prevent this (as we can not assume that people will know how to run the tests correctly)?

I found this issue here which might help: https://github.com/rust-lang/cargo/issues/2911

**Comment by sandreae** [comment]
Yeh, I added a note to the test_utils README, but you're right, we shouldn't expect everyone to do this every time.

It's the doc tests which fail, right? I think we can actually flag them all with `#[cfg(test)]` and that'll sort it as well as all features are enabled there too.

**Comment by adzialocha** [comment]
> It's the doc tests which fail, right? I think we can actually flag them all with #[cfg(test)] and that'll sort it as well as all features are enabled there too.

Yeah, its failing as the example in the doc uses the utilities of the `testing` feature. I tried adding the attribute, but then the test failes as it can't find a `main` method ..

**Comment by adzialocha** [comment]
Ah, I see now what you mean, one can have a `tests` module _inside_ `main`. Still haven't made it work though .. but I'll try!

Did you do this https://github.com/p2panda/p2panda/blob/main/p2panda-rs/src/test_utils/fixtures/operation_fixtures.rs#L235 for the same reason btw?

**Comment by adzialocha** [comment]
Maybe it is a sign we need an `examples` folder :laughing:

**Comment by sandreae** [comment]
> Ah, I see now what you mean, one can have a tests module inside main. Still haven't made it work though (I get strange "expected item" errors) .. I'll try more!

Yeh, that's what I thought, as it works here:

https://github.com/p2panda/p2panda/blob/047f0511b8c2482405bc1187479f1bac6b752d94/p2panda-rs/src/test_utils/fixtures/operation_fixtures.rs#L81-L85

But I tried it too in `documents/mod.rs` as well and it doesn't fix it.... 

There's some related chatter here: https://users.rust-lang.org/t/doctests-that-require-a-non-default-feature-is-it-possible/29529/7

**Comment by sandreae** [comment]
Ok, think I got a solution: https://github.com/p2panda/p2panda/pull/350

**Comment by adzialocha** [comment]
> Ok, think I got a solution: https://github.com/p2panda/p2panda/pull/350

Super looks good!
