### ISSUE TITLE
Tests appear multiple times

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#351]
https://github.com/p2panda/p2panda/blob/main/p2panda-rs/src/test_utils/fixtures/operation_fixtures.rs#L235

Here we test in the doc string and in a module (which doesn't have a cfg tag).

It's more of a question than an issue: @sandreae what is the pattern behind it?

**Comment by sandreae** [comment]
Ah, there's no special pattern. I just prefer to write the tests outside of the doc strings then paste them in :rofl: 

>  (which doesn't have a cfg tag)

The whole `test_utils` module is set with #[cfg(test)] so they are run as well during tests.

We can remove them though if you prefer, it is unnecessary duplication of course... There's one other place I've done the same thing too.

**Comment by adzialocha** [comment]
> We can remove them though if you prefer, it is unnecessary duplication of course... There's one other place I've done the same thing too.

Thank you! Cool, I remove it then as part of this PR: https://github.com/p2panda/p2panda/pull/350
