### ISSUE TITLE
Also store the `Operation` in `publish_entry()`

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#360]
Currently we only store the `Entry` in `publish_entry()`. It feels natural that we also store the `Operation`, let's do that.

**Comment by sandreae** [comment]
We could do this in 2 lines of code now if we like....

**Comment by adzialocha** [comment]
> We could do this in 2 lines of code now if we like....

Slightly related thought: https://github.com/p2panda/p2panda/issues/360#issuecomment-1166218270

I wonder if we could take out some functionality of publish entry in external, composable methods so they will be useful for other things as well?

**Comment by adzialocha** [comment]
I think `publish_entry` still makes sense, maybe next to something like `batch_publish_entries`, but they should be composed of flows we can also compose differently. I'd imagine something like:

```
publish_entry(entry_encoded, operation_encoded) -> Result<()> {
  insert_entry(entry_encoded)?;
  insert_operation(operation_encoded)?;
}

insert_entry(entry_encoded) -> Result<()> {
   validate_entry_encoded(entry_encoded)?;
   store.insert(entry_encoded)?;
}

...
```

This is obviously more far from what is possible with out data types, but I just want to sketch a more "onion" approach, where there is very low level, more unsafe but composable approaches, some more mid-level ones and very high-level ones close to our GraphQL API (where I'm not sure right now if it should still be called `publishEntry`?).
