### ISSUE TITLE
How verified is a `VerifiedOperation`?

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#366]
There are two constructors for `VerifiedOperation`, one accepts an encoded entry and it's operation, in the constructor these are decoded, checking that they are indeed a pair. The other constructor accepts Author, Operation and OperationId, no verification against an entry is performed.

Both approaches are valid, one assumes pre-verification, one does not. But maybe it's confusing having both, and also it raises broader questions around our validation flows.

I suggest we put the "unverified" constructor behind a testing flag for now. That's where it is most useful, and we aren't using this struct in many places yet, I think we only need the EntrySIgned + OperationEncoded constructor for now. If we hit problems with that we can reconsider.

**Comment by adzialocha** [comment]
> I suggest we put the "unverified" constructor behind a testing flag for now.

I'd like that!

The remember from the naming discussion was that an `Operation` becomes an `VerifiedOperation` in its connection with an entry, as we a) were in need of a construct which combines both and b) it covered well that `Operation` do not carry any security in terms of authenticity and integrity (only in combination with a `SignedEntry`).

**Comment by cafca** [comment]
The testing flag is fine but I don't think this is so much of a problem. The `VerifiedOperation` _represents_ a verified operation, which doesn't necessarily mean that it does the verifying itself. This should be made clear in docstrings.

**Comment by sandreae** [comment]
Yeh, I feel similar to you @cafca, that some of our structs can only represent data as it passes through our system, it's not possible for them to be aware of their "valid" status within the wider context.

I think we talked about this a little yesterday, I liked thinking about some structs (like `EntrySigned`) being the gate-keepers that we know will be facing wild data from the outside and perform validation for our core data types, then there are other types where we don'tcan't promise the same level of validation and offer constructors which are dev-friendly but less "safe".

Obvs we'd need to explain this clearly, which we don't do, so playing it safe and putting this behind a testing flag now is the right choice I think. 

We can discuss this in the validation deep dive whenever that happens :+1:

**Comment by sandreae** [comment]
I think one place where the constructor without entry<->operation verification would be useful is in `publish_entry()`. Here we validate and verify the encoded entry and operation at the start of the method, then later we want to store a `VerifiedOperation`. We don't want to have to verify everything again (which involves decoding) when building this.

**Comment by adzialocha** [comment]
> I think one place where the constructor without entry<->operation verification would be useful is in publish_entry(). Here we validate and verify the encoded entry and operation at the start of the method, then later we want to store a VerifiedOperation. We don't want to have to verify everything again (which involves decoding) when building this.

This sounds a little bit like our API is not flexible enough: We would introduce a new constructor for a certain case. I wonder if actually pushing everything into `publish_entry` is too specialized and we need something more modular we can combine for different scenarios.

Also looking at the requirements of replication (batch verification) it could be interesting to find a streamlined approach in our API where all objects provide everything to combine them in a way which gives you what you need (plus having some more high level methods which have some opiniated combinations ready for you you probably want to have).

Could we schedule a meeting about this next week? I'd love some jamming phase for this by sketching some "ideal" API flows (without looking too much at what we have right now, but I'm sure its close already).

**Comment by sandreae** [comment]
Massive :+1:

I was thinking something similar about a nice modular approach to verification too. 

Actually, we have some synchronicity as I just messaged about this issue in our chat :rofl: 

I'd love a jam on this.
