### ISSUE TITLE
`LogId(0)` 

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#369]
`bamboo` allows a log_id with value `0`. I always thought we didn't, and would start from `1`, but we don't validate against this anywhere, at the moment `LogId(0)` is accepted.

Our spec says: `every log contains up to 2^64 - 1 entries`

Shall we introduce validation to catch this case?

**Comment by adzialocha** [comment]
I think we start `seq_num` from `1` and `log_id` from `0` (following the bamboo spec, and the crate of course).

**Comment by sandreae** [comment]
Hmm, ok, I got that mixed up the. But why is `LogId::default()` starting from `1`?

And doesn't this: "every log contains up to 2^64 - 1 entries" mean 0 is not included?

**Comment by adzialocha** [comment]
> And doesn't this: "every log contains up to 2^64 - 1 entries" mean 0 is not included?

Yeah, good question! Maybe its a bug introduced from when we removed the system log_id (odd) / application log_id (even) distiction?

**Comment by adzialocha** [comment]
> Cool, then I think this issue is more about a spec update +1

Yes, and changing the `LogId::default()` to `0`.

This was the PR, and it literally just looks like something being overlooked in the change: https://github.com/p2panda/p2panda/pull/154

**Comment by adzialocha** [comment]
Good catch btw!

**Comment by cafca** [comment]
Hah, cool find! We originally planned to have log 0 specifically only for publishing schemas!
