### ISSUE TITLE
Implement wasm bindings for atomic structs and methods

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#39]

**Comment by sandreae** [comment]
I'm having a go at this locally to get my head round wasm. Got a question:

Trying to implement wasm for the `Author` struct like so:

```
#[cfg_attr(target_arch = "wasm32", wasm_bindgen)]
impl Author {
    /// Validates and wraps author string into a new `Self` instance.
    #[cfg_attr(target_arch = "wasm32", wasm_bindgen(constructor))]
    pub fn new(value: &str) -> Result<Author> {
        let author = Self(String::from(value));
        author.validate()?;
        Ok(author)
    }
}
```

Which throws an error (E0401) because it doesn't like `Self`:

> use of generic parameter from outer function use a type here instead

So i tried using `Author` instead of Self which throws a different error (E0277):

> the trait `IntoWasmAbi` is not implemented for `std::result::Result<Author, anyhow::Error>`

So there is an issue with what's being returned in the `Result` object, right? Which should be something wasm likes. Am I at least on the correct error path....?

**Comment by adzialocha** [comment]
@sandreae yeah, this looks good! 

Stupid with that Result type, either there is a feature flag in `anyhow` we could enable to get wasm support (I doubt it exists after checking for quickly), OR we introduce a method only for wasm contexts (see `verify` method in `key_pair.rs` as an example) but then we will need to do this a lot .. OR we have to use a different `Result` type which hurts but maybe there is an elegant solution I can't think of right now.

**Comment by sandreae** [comment]
Hmmm, OK... So the problem is with the `anyhow` error rather than returning a `Result`. I'll do some digging to see how others deal with this situation, and check out the `key_pairs` method. Thanks!

**Comment by sandreae** [comment]
For reference: https://rustwasm.github.io/docs/wasm-bindgen/reference/types/result.html?highlight=Result#resultt-jsvalue

**Comment by sandreae** [comment]
From this issue it sounds like `anyhow` should work with `wasm`...?

https://github.com/dtolnay/anyhow/issues/115

**Comment by adzialocha** [comment]
> From this issue it sounds like `anyhow` should work with `wasm`...?
> 
> https://github.com/dtolnay/anyhow/issues/115

Yeah, I was also wondering, or it can be understood as "it's not supported therefore it's not a problem"?

**Comment by sandreae** [comment]
Haha, yeh, I'm not sure either.... Seems like there are a lot of conversations/issues/PRs around how best to handle error handling with wasm.

**Comment by adzialocha** [comment]
This problem seems to overlap with my general Error type refactoring, I started something some days ago, let me see of I can make sense of this taking wasm into account (also I'll share the code soon).

**Comment by sandreae** [comment]
Cool. I had a go at refactor the error handling in `author` to use `Result` and `Error` from the standard library (just for my own learning really), I got to the same problem with needing to return wasm compatible `JsValue`. Not confident I was actually solving any problem....

**Comment by adzialocha** [comment]
Meh, it looks like there is no good path here (https://github.com/rustwasm/wasm-bindgen/issues/1742) :cry:

I'm not really sure what to do, maybe there is a way to implement a macro handling the error return types accordingly to the current compilation target but I don't know if this isn't overcomplicating things even more or if this even possible?

The "easiest" and also ugliest solution is to to check the target and have every method twice with different error types..:

```rust
#[cfg(not(target_arch = "wasm32"))]
pub fn test() -> Result<String, SomeError> {
    Err(SomeError::Ouch)
}

#[cfg_attr(target_arch = "wasm32", wasm_bindgen)]
pub fn test() -> Result<String, JsValue> {
    Err(js_sys::Error::new("Hello, wasm!").into())
}
```

**Comment by adzialocha** [comment]
Or we have to think about the wasm interface completly different. Maybe we don't need to export *every* method as we do in Rust but rather think of special only-wasm methods in a `wasm` module which combine them? Something like `createAndSignEntry(keyPair, message)` and `createMessage()` etc.

**Comment by sandreae** [comment]
> Maybe we don't need to export every method as we do in Rust but rather think of special only-wasm methods in a wasm module which combine them?

This might be a good approach, from what I'm reading it seems to be accepted practice to expose as little as possible via wasm.

**Comment by adzialocha** [comment]
I suggest we close this issue and come up with more detailled, multiple issues concerning what we actually want the wasm module to offer?

**Comment by cafca** [comment]
related: https://hackmd.io/kRb3ma1AQhyhMCQKBnBTKQ
