### ISSUE TITLE
`MemoryStore` use outside of test utilities

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#391]
`MemoryStore` which is used in the mock `Node` could be offered as an in-memory store for p2panda clients. What steps need to be taken to make this a not-only-for-testing store?

- it needs to have full parity with `SqlStore` in `aquadoggo`
  - currently behaviour around some db interactions are different, especially around handling duplicate inserts (this doesn't error in `memoryStore` and if foreign keys are missing.
-  run testing suites against _both_ implementations. We would need a way to run a set of test suites against both implementations
- all this suggests that maybe `SqlStore` and `MemoryStore` should live together in their own crate if we want them to be equal and swappable.

**Comment by adzialocha** [comment]
Just a note: This is slightly tied to the https://github.com/p2panda/p2panda/issues/253 discussion .. how "low-level" or "high-level" do we want our crates to be?
