### ISSUE TITLE
Unexpected behaviour of `SeqNum` and `LogId` iterators

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#403]
https://github.com/p2panda/p2panda/blob/4829a162674629469f19c21e83e672e65b71162a/p2panda-rs/src/entry/seq_num.rs#L102-L108

* It always returns `Some`, but what about when the end of `u64` is reached?
   ```
   thread 'main' panicked at 'attempt to add with overflow', /home/adz/.cargo/registry/src/github.com-1ecc6299db9ec823/p2panda-rs-0.4.0/src/entry/seq_num.rs:106:19
   ```
* It actually doesn't iterate!
    ```rust
    use p2panda_rs::entry::SeqNum;
    
    fn main() {
        let a = SeqNum::new(5).unwrap();
        let mut iter = a.into_iter();
        let result = iter.next();
        println!("{:?}", result);
        let result = iter.next();
        println!("{:?}", result);
    }
    ```

    Leads to:
    
    ```
    Some(SeqNum(6))
    Some(SeqNum(6))
    ```

**Comment by adzialocha** [comment]
This makes me also wonder if `LogId` has a similar issue?

**Comment by adzialocha** [comment]
@sandreae :sweat_smile:

**Comment by adzialocha** [comment]
LogId looks similar :-D

```rust
    #[test]
    fn log_ids() {
        let mut log_id = LogId::default();


        let mut next_log_id = log_id.next().unwrap();
        assert_eq!(next_log_id, LogId::new(1));


        let next_log_id = next_log_id.next().unwrap();
        assert_eq!(next_log_id, LogId::new(2));
    }
    ```

**Comment by cafca** [comment]
🙄

**Comment by cafca** [comment]
What do you think about the validation code in this section? ;-)

https://github.com/p2panda/p2panda/blob/4829a162674629469f19c21e83e672e65b71162a/p2panda-rs/src/entry/log_id.rs#L15-L19

**Comment by adzialocha** [comment]
> What do you think about the validation code in this section? ;-)
> 
> https://github.com/p2panda/p2panda/blob/4829a162674629469f19c21e83e672e65b71162a/p2panda-rs/src/entry/log_id.rs#L15-L19

Haha, fantastic! The comment is old actually and can be updated. We do not need to validate anymore as the value will be between 0 and U64::MAX automatically.
