### ISSUE TITLE
Validate name in `SchemaId`

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#425]
Our specification prescribes a certain format for the name in schema ids, this is currently only checked when looking at operations and not validated when creating `SchemaId` instances.

**Comment by sandreae** [comment]
@adzialocha do you remember where is this checked in the operation flow?

**Comment by adzialocha** [comment]
Generally speaking we validate any struct instances _always_ in two places in `p2panda-rs`:

1. Creating new instances after deserialization
2. Creating new instances programmatically

Most of validation can happen within constructors or `Deserialize` implementations. This implies of course that we can only validate things we have information about, so for example validating log integrity is only possible when you have all data about the backlinks and skiplinks. For these cases (where a _combination_ of data is required), there are individual `validate_x` methods which need to be called "manually".

In the operation flow this is programatically ensured for `SchemaId` via type safety: https://github.com/p2panda/p2panda/blob/309c452da6df107a63dcd17df0c9addcf2f8a66b/p2panda-rs/src/operation/operation.rs#L29 - assuming that the `SchemaId` constructor does all the necessary validation. In terms of deserialization this should be ensured via: 

1. Deserialization into `PlainOperation` which contains `SchemaId`: https://github.com/p2panda/p2panda/blob/309c452da6df107a63dcd17df0c9addcf2f8a66b/p2panda-rs/src/operation/plain/plain_operation.rs#L81-L83
2. Deserialization of `SchemaId`: https://github.com/p2panda/p2panda/blob/309c452da6df107a63dcd17df0c9addcf2f8a66b/p2panda-rs/src/schema/schema_id.rs#L221-L245 which calls the constructor
3. Validation within the constructor: https://github.com/p2panda/p2panda/blob/309c452da6df107a63dcd17df0c9addcf2f8a66b/p2panda-rs/src/schema/schema_id.rs#L159-L164

I guess one can write a test to see if that is all actually working :laughing: (if there is not already one, haven't checked).

**Comment by sandreae** [comment]
As far as I can see, the implementation follows the spec well. We're concerned with requirement [`SC1`](https://p2panda.org/specification/data-types/schemas) although in the spec the same conditions are mentioned in requirement `SC9` we should avoid this slightly confusing duplication if possible.

This is the name validation method:

https://github.com/p2panda/p2panda/blob/423a58c2a1cd456d2580ec768ab108b01dfc89ec/p2panda-rs/src/schema/validate/schema_definition.rs#L9-L22

Tested here:

https://github.com/p2panda/p2panda/blob/423a58c2a1cd456d2580ec768ab108b01dfc89ec/p2panda-rs/src/schema/validate/schema_definition.rs#L161-L191

And it's used in the constructor for `SchemaId` and when deserialising.

I'll add a few more tests to show this is checked thoroughly during deserialisation in a couple of places.

Don't think there is anything extra to implement though.
