### ISSUE TITLE
Validate description, fields and name in `Schema`

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#426]
Whenever we create a `Schema` instance we should check if the description, schema name and field names are following the specification.

**Comment by adzialocha** [comment]
I suggest we introduce new `FieldName` and `SchemaDescription` and `SchemaName` structs which in themselves have `Validate` implementations checking the necessary things

**Comment by sandreae** [comment]
Hmm... I introduced a `SchemaName` struct in the above linked PR, it makes sense and easy to see what validation occurs for the name part of a schema id. However doing the same for `FieldName`, `SchemaDescription`, `SchemaFields` and `FieldType` now looks a bit overkill.... Maybe the benefits of having more consistency across the code base is lost in adding so many extra "single use" types.... @adzialocha any preference? Right now I'm preferring just leaving as is and not adding any new types. It's a slightly different more functional pattern in this module but equally easy to read and understand.

**Comment by adzialocha** [comment]
> Hmm... I introduced a `SchemaName` struct in the above linked PR, it makes sense and is easy to see what validation occurs for the name part of a schema id. However doing the same for `FieldName`, `SchemaDescription`, `SchemaFields` and `FieldType` now looks a bit overkill.... Maybe the benefits of having more consistency across the code base is lost in adding so many extra "single use" types.... @adzialocha any preference? Right now I'm preferring just leaving as is and not adding any new types. It's a slightly different more functional pattern in this module but equally easy to read and understand. 

Sounds good to me 👍🏻 as long as all validation is handled from all ends it's good to not over engineer it.

**Comment by adzialocha** [comment]
> Whenever we create a `Schema` instance we should check if the description, schema name and field names are following the specification.

Just checking, is this implemented?

**Comment by sandreae** [comment]
Ugh, no, it is not. I was way to focused on `SchemaId` thinking the problem was there.... 

https://github.com/p2panda/p2panda/blob/0fdb7d05fb971e0d6fb9910762119f93a064a0af/p2panda-rs/src/schema/schema.rs#L83-L105

**Comment by sandreae** [comment]
https://github.com/p2panda/p2panda/blob/0fdb7d05fb971e0d6fb9910762119f93a064a0af/p2panda-rs/src/schema/schema.rs#L38-L52

https://github.com/p2panda/p2panda/blob/0fdb7d05fb971e0d6fb9910762119f93a064a0af/p2panda-rs/src/schema/schema.rs#L410-L424

**Comment by sandreae** [comment]
> I suggest we introduce new `FieldName` and `SchemaDescription` and `SchemaName` structs which in themselves have `Validate` implementations checking the necessary things

Indeed this is the right way to go :+1:
