### ISSUE TITLE
Nice way to go from `EncodedOperation` to `Operation` for testing

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#435]
No `Schema` no validation.

Am I stupid? I am incapable of finding a nice way to do this :rofl: help

**Comment by adzialocha** [comment]
.. not possible, soooooorrey 🤣 operations are untagged now, we don't have the information we need without schemas.

**Comment by adzialocha** [comment]
You could do something very hacky and guess the content by regexing if its a relation etc. but this smells like a hack we will hate to work with in 3 months 😅

**Comment by adzialocha** [comment]
Or you have something limited to unambiguous types like pinned relation lists, numbers and bool.

**Comment by adzialocha** [comment]
> Or you have something limited to unambiguous types like pinned relation lists, numbers and bool.

☝️Also not future proof as we might introduce more types which look similar in the future.

**Comment by sandreae** [comment]
Ok, no, sounds horrible, give up on this. Will just look at the testing flow and change that :+1:
