### ISSUE TITLE
Visibility of `EncodedEntry` and `EncodedOperation` constructors

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#442]
I could access the test constructors in `aquadoggo` outside of the test feature, and are the `from_bytes` constructors supposed to be private?

**Comment by adzialocha** [comment]
Both structs do not supply any validation whatsoever, any byte sequence can be simply deserialized into them.

Validation is too early at this stage, we do this as soon as we're decoding.

This is why exposing from_bytes makes sense, it doesn't give or take any guarantees, other than what serde already does.

Why the cfg attribute doesn't work I don't know though, that's kinda scary 😬

**Comment by adzialocha** [comment]
Slightly unrelated: I'd be up for implementing `FromStr` publicly on them. I thought that serde would handle deserializing from hex strings for us (given that it's a human readable encoding format like JSON or GraphQL), but we don't use serde in scalars ..

**Comment by adzialocha** [comment]
Slightly unrelated: I'd be up for implementing `FromStr` publicly on them. I thought that serde would handle deserializing from hex strings for us (given that it's a human readable encoding format like JSON or GraphQL), but we don't use serde in scalars ..

.. another solution is to simply use `hex::decode`

**Comment by sandreae** [comment]
> This is why exposing from_bytes makes sense, it doesn't give or take any guarantees, other than what serde already does.

Thanks for the comments! I think I phrased the second point badly. I meant that as I understand it `from_bytes` is currently private (to the crate `p2panda-rs`) so it can't be used in `aquadoggo`.

I agree with what you say about it above and the general idea of these structs (simple wrappers).

**Comment by adzialocha** [comment]
> Thanks for the comments! I think I phrased the second point badly. I meant that as I understand it `from_bytes` is currently private (to the crate `p2panda-rs`) so it can't be used in `aquadoggo`.

Should we make that public and use hex::decode in the doggo?

**Comment by sandreae** [comment]
> Should we make that public and use hex::decode in the doggo?

Yeh, sounds good!

**Comment by sandreae** [comment]
Good news `from_str` seems to be hidden again for me in non-test code, no idea why that happened but maybe just local to my environment...

**Comment by sandreae** [comment]
(do you mind checking on your end too though?)
