### ISSUE TITLE
Logic for backlink_seq_num and skiplink_seq_num in SeqNum

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#45]
It looks to me like there is something funny going on in the logic for calculating `skiplink_seq_num` and `backlink_seq_num` in `SeqNum`. I added a failing test to the experimental branch to demonstrate. As I understand it if the entries `seq_num` is 2 then both `backlink_seq_num` and `backlink_seq_num` should both equal `1`.

https://github.com/p2panda/p2panda/blob/7a092ee5d6c57a97111e06e5e2ebf245c6efa592/p2panda-rs/src/atomic/seq_num.rs#L118-L124

Reference lipmaa tests can be seen here: https://github.com/pietgeursen/lipmaa-link/blob/master/src/lib.rs

Seems like we're being inconsistent with how we're offsetting the return values with `FIRST_SEQ_NUM`.

Maybe I'm misunderstanding how these methods are to be used though...

**Comment by sandreae** [comment]
Fixed with: https://github.com/p2panda/p2panda/commit/d9dcf5d691b1bfc8e9dd17b49207d17488ffa0ff#diff-78d9967165ed174c5073e5e4ce628be7be9d6bdde364fb23b18b5f45cfb9d748

**Comment by adzialocha** [comment]
Upsi. Just noticed that this landed in the experimental branch, can you make a PR with this commit only? (you could cherry pick it!) 🙂
