### ISSUE TITLE
Error when bundled with webpack: "keypair_new" undefined

### ISSUE THREAD

**Issue by nmauersberg** [p2panda/p2panda#462]
Hey hey :)
I wanted to use p2panda in a new Next.js project, but the generate keypair example throws an error:

`Uncaught Error: Could not generate new key pair: Cannot read properties of undefined (reading 'keypair_new')`

It seems to be an issue with webpack, it also happened in a Create-React-App project, or a simple webpack setup. Here is a simple example, to reproduce the error: https://github.com/nmauersberg/p2panda-keypair

I am really excited about what you're building and looking forward to trying it out, when this issue is resolved.
Cheers

**Comment by sandreae** [comment]
Hi @nmauersberg, great you are keen to use p2panda, thanks for raising this issue!

I had a look at the example repo and can see you're just missing a required step which initialises the WebAssembly code. Once I added that everything worked fine (see below). Check out [this](https://github.com/p2panda/p2panda/tree/main/p2panda-js#usage) section of the readme for more details. 

```javascript
import { initWebAssembly, KeyPair } from 'p2panda-js';

initWebAssembly().then(() => {
    const keyPair = new KeyPair();
    console.log(keyPair.publicKey());
});
```

**Comment by nmauersberg** [comment]
Ah yes, thank you very much for the quick reaction!
Have a great weekend!

**Comment by sandreae** [comment]
You too, enjoy!

**Comment by adzialocha** [comment]
> Ah yes, thank you very much for the quick reaction!
> Have a great weekend!

You should come to our small p2panda celebration tomorrow at 6pm @nmauersberg ! Just write us a mail to contributors@p2panda.org if you have time 🙃

**Comment by nmauersberg** [comment]
@adzialocha I'd love to come, but I am currently in Bulgaria.

I'll come to the next Mondays Meetup after we are back to Germany, in a few weeks.

See you in the Rocket Chat till then. :)

Have a great pary!
