### ISSUE TITLE
Typed errors for `validation` and `domain` modules

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#466]
Currently these modules are in `test_utils` and used by `MemoryStore`. We would like to export them for use elsewhere though (eg. `aquadoggo`). For this we need typed errors.

**Comment by adzialocha** [comment]
For most of `aquadoggo` we don't need typed errors as they are merely just text strings in api responses, but since `domain` and `validation` might be moved to p2panda one day it makes sense to make it ergonomic for error handling.

**Comment by adzialocha** [comment]
On this note, doesn't this need to be in the `aquadoggo` repository?

**Comment by sandreae** [comment]
> For most of aquadoggo we don't need typed errors as they are merely just text strings in api responses, but since domain and validation might be moved to p2panda one day it makes sense to make it ergonomic for error handling.

I'm talking about `domain` and `validation` in `p2panda-rs`. They sit in `test_utils` right now, but it would be good to move them out so we can export them for use in aquadoggo. One thing required for this is nicer error handling which is what this issue is about.

I'll add this to the description :+1:

**Comment by adzialocha** [comment]
Ah, sorry! Thanks for clarifying 👍
