### ISSUE TITLE
Rename `WithOperationID` trait to `WithId`

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#467]

**Comment by adzialocha** [comment]
I guess that would require us needing to introduce a trait over all our `EntryHash` wrapper types as well.

Later we could even consider making the hashing function generic, but that's a separate issue.

**Comment by sandreae** [comment]
I wonder if we could approach it like `WithId<OperationId>`, `WithId<DocumentId>`, `WithId<SchemaId>` 

In cases where the id type can be inferred then a call to `id()` returns the suitable id. In ambiguous case we can call the trait method explicitly like `WithId::<DocumentId>::id(operation)`

**Comment by adzialocha** [comment]
> I wonder if we could approach it like `WithId<OperationId>`, `WithId<DocumentId>`, `WithId<SchemaId>` 
> 
> In cases where the id type can be inferred then a call to `id()` returns the suitable id. In ambiguous case we can call the trait method explicitly like `WithId::<DocumentId>::id(operation)`

Uhh, that's nice!

**Comment by sandreae** [comment]
I already tested it out, and it is quite nice ;-p
