### ISSUE TITLE
Export `domain` and `validation` modules publicly

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#479]
We initially created these modules in `aquadoggo`, together they expose the api for the validation and storage of p2panda data. The reasons for bringing them into p2panda-rs are:
- they are generic so can be used in other node implementations
- they could be exported to wasm one day
- we already use them in `test_util` but as it is now this is a large amount of code duplication which is hard to maintain
- it's nice to have the validation flows defined in our spec also expressed here in `p2panda-rs`
- it's not much work, just moving things around

I would suggest creating a new module named `api` containing `publish.rs` and `next_args.rs` and `validation.rs`. Breaking up the concrete steps within `publish` and `next_args` into their own methods would also be nice.

**Comment by adzialocha** [comment]
`api` sounds good 👍🏻
