### ISSUE TITLE
Drop the `-rs` from the crate name

### ISSUE THREAD

**Issue by ijsnow** [p2panda/p2panda#509]
I suggest dropping the `-rs` from the crate name in the `Cargo.toml` file while `p2panda` is still available on crates.io. As the library gains popularity nefarious actors could claim `p2panda` and people could install it unintentionally as its the simpler variation. In addition to a supply chain attack vector, it's just redundant/not necessary to have the file type for the language its written in in a library name. No change to the repository directory structure/naming is necessary, just drop the `-rs` in `Cargo.toml` and publishing.

**Comment by adzialocha** [comment]
We should consider the same for our `-js` library

**Comment by adzialocha** [comment]
Superseded by new crate naming scheme, for example via https://github.com/p2panda/p2panda/pull/535
