### ISSUE TITLE
Deserialization of `DocumentViewId` hex strings broken: `invalid type: string, expected byte buffer`

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#528]
I could reproduce the behaviour in this branch: https://github.com/p2panda/p2panda/pull/529

**Comment by adzialocha** [comment]
Ah, after some digging it looks like it so far concerns only `DocumentViewId`

**Comment by sandreae** [comment]
Just had a quick look. Shouldn't the test value for `deserialize_human_readable` be an array of hex encoded hashes? Like so:

```rust
let json = format!(
    r#"
    {{
        "document_view_id": ["{hash_str}"]
    }}
"#
);
```

**Comment by adzialocha** [comment]
> Just had a quick look. Shouldn't the test value for `deserialize_human_readable` be an array of hex encoded hashes? Like so:
> 
> ```rust
> let json = format!(
>     r#"
>     {{
>         "document_view_id": ["{hash_str}"]
>     }}
> "#
> );
> ```

There's no JSON we have like that (GraphQL responses etc.), only in this form: `<id>_<id>`. I had a go at a new `Visitor` which fixes the problem for view ids.

**Comment by sandreae** [comment]
> > Just had a quick look. Shouldn't the test value for `deserialize_human_readable` be an array of hex encoded hashes? Like so:
> > ```rust
> > let json = format!(
> >     r#"
> >     {{
> >         "document_view_id": ["{hash_str}"]
> >     }}
> > "#
> > );
> > ```
> 
> There's no JSON we have like that (GraphQL responses etc.), only in this form: `"<id>_<id>"`. I had a go at a new `Visitor` which fixes the problem for view ids, can push later.

Ah yeh, of course!

**Comment by adzialocha** [comment]
> > > Just had a quick look. Shouldn't the test value for `deserialize_human_readable` be an array of hex encoded hashes? Like so:
> > > ```rust
> > > let json = format!(
> > >     r#"
> > >     {{
> > >         "document_view_id": ["{hash_str}"]
> > >     }}
> > > "#
> > > );
> > > ```
> > 
> > There's no JSON we have like that (GraphQL responses etc.), only in this form: `"<id>_<id>"`. I had a go at a new `Visitor` which fixes the problem for view ids, can push later.
> 
> Ah yeh, of course!

Still a good answer to why it fails 🤣: arrays are not strings (at least not on that level)!
