### ISSUE TITLE
[FR/Question] Build distributed apps

### ISSUE THREAD

**Issue by kacperpaczos** [p2panda/p2panda#533]
Technically, does p2panda have the ability to share data between computers over the Internet in a secure manner?

That is: will this be supported in the future?

Does p2panda have plans for local networks only?

https://iroh.computer/

**Comment by adzialocha** [comment]
Hi @kacperpaczos!

> Technically, does p2panda have the ability to share data between computers over the Internet in a secure manner?
> 
> That is: will this be supported in the future?

Yes, that feature is supported and implemented in https://github.com/p2panda/aquadoggo/! We support discovery, p2p connectivity and replication over the Internet as well.

> Does p2panda have plans for local networks only?
> 
> https://iroh.computer/

Currently we're using libp2p for all networking, but Iroh is definitely an exciting alternative!
