### ISSUE TITLE
`TopicMap` should not be fully generic but require to implement `HashMap<PublicKey, T>` instead

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#627]

**Comment by sandreae** [comment]
I'm not sure if this change is to move the current `TopicMap` from `lib.rs` into `log_sync` module and make it specific to that protocol, or rather create a new `LogHeightTopicMap` in that module, leaving the generic version in place. I like the docs for the generic version, and this mapping of query to data scope is a pattern which will occur regularly. However we don't strictly need to provide a trait for that, except that we want to document this behaviour somewhere.

I suggest leaving the generic version in place, even though it's not used anywhere, and creating a new less generic version in `log_sync` module. It isn't doing any harm and we can reflect a little longer on what it means to provide this trait.

**Comment by adzialocha** [comment]
The most important thing is that the type of the interface to-be-implemented is directly visible and well documented, as this is what is currently not clear when implementing against the API.

If we keep the old trait or not I'm undecided, though usually I think it's good to remove code which currently doesn't have a use (I'm sure the docs can still fit in the new type as a general description of the problem).

Lastly I'd call it a `TopicLogMap` as I don't think it has something to do with "Log Height"?

**Comment by adzialocha** [comment]
I was thinking about it a little more and was wondering if we actually _always_ want the type to be `HashMap<PublicKey, T>` in any sync protocol implementation?

```rust
pub trait TopicMap<T, S>: Debug + Send + Sync
where
    T: TopicQuery,
{
    async fn get(&self, topic: &T) -> Option<HashMap<PublicKey, S>>;
}
```

It essentially just means that the return type should be your data type(s) grouped per author?
