### ISSUE TITLE
Implement `Schema` struct with methods to create and validate messages with user schemas

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#74]

**Comment by sandreae** [comment]
Thought I might have a go at this, is the general idea that we want a struct which:

- is initiated with a user schema
- has method/s for creating messages based on active user schema
- has a method for validating messages against active user schema

Does that sound about right?

I was wondering where the actual CBOR schema creation should happen too (I don't think that's implemented yet right? Or did I miss it....?). Maybe that could be here as well, for now at least.

**Comment by adzialocha** [comment]
Yeah, for this it might make sense to start drafting an API first, maybe with a "fake" JavaScript / Rust example on how we imagine this to be used.

**Comment by sandreae** [comment]
Yep, having a go now :+1:

One thing I want to clarify already.... What we're validating with `UserSchema`s is actually the `MessageFields` data, right? The `Message` itself is validated by the meta `MESSAGE_SCHEMA` which is currently hard-coded. Orrr...???

**Comment by adzialocha** [comment]
There is some thoughts around how to approach this, but take it as a first initial idea, haven't thought this through yet:

All validation is done via CDDL, meaning that the aquadoggo receives messages encoded as CBOR which directly gets validated via CDDL.

Since every message follows the "message" schema and then embedding a custom "user" schema there can be two ways to validate them:

1. Check the data for a valid message schema, then check the content of it for its correct user schema
2. Have a cool CDDL which does both at the same time

For point 2. one could make use of the CDDL "sockets" https://datatracker.ietf.org/doc/html/rfc8610#section-3.9 which allows us to simply concatenate CDDL strings. With this we would end up with one very large CDDL definition which contains the "message" schema and then all the user and system schemas this aquadoggo supports. When the node maintainer adds / removes schemas the CDDL will accordingly be updated eg. newly concatenated with the latest setting.

I don't really know what an elegant approach would be for implementing this but I'd prefer strategy No. 2 as I can imagine we will have some performance benefits from doing the CDDL validation only once per incoming message.

With this we would need something which spits out the "final" concatenated CDDL schema while still allowing building / validating custom user schemas individually.

Some pseudo code sketch could be:

```
// "Hardcoded" protocol schemas for p2panda version 1
const MESSAGE_SCHEMA_v1 = "..."
const SYSTEM_SCHEMA_PERSONAS_v1 = "..."
const SYSTEM_SCHEMA_MIGRATIONS_v1 = "..."
const SYSTEM_SCHEMA_BLA.. = "..."

// Something I just created for myself
const myCustomUserSchema = new Schema({
  title: "text",
  birthday: "date",
});

const isValid = myCustomUserSchema.validate(someEncodedMessage);

// This automatically returns the CDDL string (could be built via https://github.com/anweiss/cddl/blob/main/src/ast.rs based on the message fields of this schema)
const cddl = myCustomUserSchema.getCDDL();

const finalCddl = concatenateAllSchemas([
MESSAGE_SCHEMA_v1,
SYSTEM_SCHEMA_PERSONAS_v1,
SYSTEM_SCHEMA_MIGRATIONS_v1,
SYSTEM_SCHEMA_BLA...,
myCustomUserSchema.getCDDL()])

// Somewhere in aquadoggo during replication / RPC call..
validateIncomingMessage(finalCddl, someEncodedMessage)
```

Writing the above pseudo-code I don't really think this is a good approach, but you might get the idea :sweat_smile:

**Comment by sandreae** [comment]
Great, thanks for this, makes sense and is roughly what I was thinking it would look like. I like the idea of a massive everything-in-one cddl file 😁

I've mainly been thinking about the client side UserSchema creation and validation and that UserSchema's could be constructed in a similar way to how are are doing MessageFields. I can post some code examples later, on my phone now.

Thanks!

**Comment by cafca** [comment]
> I like the idea of a massive everything-in-one cddl file 😁

you .. like that? 😅

**Comment by sandreae** [comment]
Haha, yeh, weird right???

**Comment by sandreae** [comment]
I think I've gone slightly off track because... learning about CDDL (and Rust :rofl: ).... but here is some example code for an api which can be used for building CDDL schemas:

```rust

// Create a new empty schema
let mut house = CDDLSchema::new();

// Add an entry which with a key of "house" and a CDDL type of int
house
    .add_entry("number", CDDLValue::Type(CDDLType::Int))
    .unwrap();

// Create a CDDL group named "animal"
let mut animal = CDDLGroup::new(String::from("person"));

// Add entries to the group
animal.add_entry("species", CDDLValue::Type(CDDLType::Tstr)).unwrap();
animal.add_entry("name", CDDLValue::Type(CDDLType::Tstr)).unwrap();

// Create group named "person"
let mut person = CDDLGroup::new(String::from("person"));

// Add properties
person
    .add_entry("name", CDDLValue::Type(CDDLType::Tstr))
    .unwrap();
person
    .add_entry("age", CDDLValue::Type(CDDLType::Int))
    .unwrap();

// Add an entry which is a CDDL Struct which maps to the "person" group
house.add_entry("owner", CDDLValue::Struct(person.clone())).unwrap();

// Add an entry which is a CDDL Struct which maps to the "animal" group
house.add_entry("pet", CDDLValue::Struct(animal.clone())).unwrap();

// Add an entry which is a CDDL Array of the "person" group
house.add_entry("residents", CDDLValue::Array(person)).unwrap();
```

**Comment by sandreae** [comment]
Each of the structs used above implements `std::fmt::Display` in a smart way to output the correct CDDL strings when formatted. It could be extended to include all the other nice CDDL goodness.

**Comment by sandreae** [comment]
However I'm not really sure how often we are imagining schemas being created... I suppose it will mostly be a set of schemas created for a particular app, in which case it might be ok to rely more on raw CDDL. However if there are cases where schema creation is something more dynamic, then an API like this could be really nice.

**Comment by sandreae** [comment]
Like a schema creating CLI **cough** _fishyfish_ **cough** **cough**

**Comment by sandreae** [comment]
```rust

let mut person_schema = CDDLSchema::new(String::from("person"));
person_schema
    .add_entry("name", CDDLValue::Type(CDDLType::Tstr))
    .unwrap();
person_schema
    .add_entry("age", CDDLValue::Type(CDDLType::Int))
    .unwrap();

print!("{}", person_schema);
// => person = { age : { type: "int", value: int }, name : { type: "str", value: tstr } }

let mut me = MessageFields::new();
me.add("name", MessageValue::Text("Sam".to_owned()))
    .unwrap();
me.add("age", MessageValue::Integer(35)).unwrap();

let me_encoded = serde_cbor::to_vec(&me).unwrap();

assert!(person_schema.validate_message(me_encoded).is_ok());
```

**Comment by sandreae** [comment]
This is where I've been experimenting:

https://github.com/p2panda/p2panda/blob/schema-playground/p2panda-rs/src/schema/schema.rs

**Comment by adzialocha** [comment]
> https://github.com/p2panda/p2panda/blob/schema-playground/p2panda-rs/src/schema/schema.rs

Yeah, well done! I didn't have time to look closely into this yet, but wondering if it makes sense to use the cddl crate for some of the functionality? Or does it not provide what we need?

**Comment by sandreae** [comment]
Yeh, I think you might be right, I took a look at the cddl crate but basically didn't understand how to do what I wanted with it so started trying to build something myself, one thing led to another, and I got hooked.... So this became a learning experience as much as anything else.

Let's discus what is useful here for what we want to do and then see if actually cddl does what we want :+1:

**Comment by sandreae** [comment]
Haha! Just looked at the cddl crate again, and now i totally get it. All that learning paid off :rofl:

**Comment by sandreae** [comment]
More code:

```rust
  // Create new empty schema
  let mut schema_1 = UserSchema::new();
  //Add message fields
  schema_1.add_message_field("first-name", FieldTypes::Str);
  schema_1.add_message_field("last-name", FieldTypes::Str);
  schema_1.add_optional_message_field("age", FieldTypes::Int);
  // Matching CDDL schema string
  let cddl_str = "
      my_rule = { 
          first-name: { type: \"str\", value: tstr, }, 
          last-name: { type: \"str\", value: tstr, }, 
          ? age: { type: \"int\", value: int, }, 
      }\n
  ";
  // Create new schema from CDDL string
  let schema_2 = UserSchema::new_from_string(&cddl_str.to_string()).unwrap();
  // should be equal
  assert_eq!(schema_2.get_schema(), schema_1.get_schema());
```

**Comment by sandreae** [comment]
https://github.com/p2panda/p2panda/blob/a516e309ba4b237913493483f4065c281e794673/p2panda-rs/src/schema/schema.rs#L266-L297
