### ISSUE TITLE
Set matching node versions in package.json and .nvmrc

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#83]
`.nvmrc` specifies v15.13.0 and package.json says v12.0.0

**Comment by adzialocha** [comment]
Is this a bad thing though? `.nvmrc` automatically sets the version to v15 on a computer working with `nvm`. The `engine` field in `package.json` just specifies the supported node version which in our case is `>12.0.0` aka, minimum version 12. Both informations are valid and true?

**Comment by cafca** [comment]
I wasn't sure whether we actually support node 12 and wanted to test that. I thought we had set it to 15 in `.nvmrc` because that's what we need and not updated `package.json`.

I just did a quick test run on v12 and it seems to be fine though, so feel free to close this issue.

I also set up a test matrix using the oldest, recommended and latest node version to test all of those at #98 . Let me know what you think.

**Comment by adzialocha** [comment]
> I wasn't sure whether we actually support node 12 and wanted to test that. I thought we had set it to 15 in `.nvmrc` because that's what we need and not updated `package.json`.

Ah, ja, this makes sense! I've always been developing on Node 12 actually and changed recently to 15 :smile_cat:
