### ISSUE TITLE
Revisit singleton logic in WASM import

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#88]
We have multiple places where we treat the wasm import as a singleton, we should revisit this and find out if we actually only need it once: :sweat_smile: 

https://github.com/p2panda/p2panda/blob/main/p2panda-js/src/wasm.ts#L12-L27
https://github.com/p2panda/p2panda/blob/main/p2panda-js/src/wasm-adapter/node.ts#L3-L5
https://github.com/p2panda/p2panda/blob/main/p2panda-js/src/session.ts#L116-L132

**Comment by adzialocha** [comment]
I've had a look at this the other day but ran into some weird TypeScript / Webpack building issues. @cafca, would you like to look at this together? I can imagine you might understand better what is going on in the Typeyverse

**Comment by cafca** [comment]
Sure! I have a meeting now and then I'm free from ~2.15pm.
